### ISSUE TITLE
华为vr glass

### ISSUE THREAD

**Issue by bizhou78** [Igalia/wolvic#1058] opened 2023-10-10 00:09 UTC
华为vrglass  全版本都无法使用，无法显示手柄和输入界面，请问是什么原因导致的？我在官网上看到软件支持鸿蒙系统并支持我的硬件设备，但安装之后就有各种问题，我咨询过大部分人使用过你们软件的人，他们的反馈也和我的问题一致，也是无法显示输入界面。请尽快修复并上架华为vrglass 的测试可用版本，谢谢！

**Comment by HollowMan6** [comment] 2023-10-10 08:51
Hi. I think this is a duplicate of #1053, so let's continue our discussion there.

And please use English when you open any issue/continue your discussion here.
这里是一个国际化的社区；并且团队里只有我会说中文，所以请使用英语方便沟通。

**Closed by HollowMan6** 2023-10-10 08:51 UTC

**Comment by bizhou78** [comment] 2023-10-19 23:43
Hello, when I used Huawei vrglass to use the latest version 1.5wolvic, I found that the handle was not displayed, and the following input boxes and function options could not be displayed. I think it is necessary for me to report this error, and I hope the engineer can fix the problem I reported. Thank you for your hard work in developing this software and the software in China. Thank you again for your efforts!I sent it to my phone-------- 原始邮件 --------发件人： Hollow Man ***@***.***>日期： 2023年10月10日周二 16:51收件人： Igalia/wolvic ***@***.***>抄送： bizhou78 ***@***.***>, Author ***@***.***>主    题： Re: [Igalia/wolvic] 华为vr glass (Issue #1058)
Hi. I think this is a duplicate of #1053, so let's continue our discussion there.
And please use English when you open any issue/continue your discussion here.
这里是一个国际化的社区；并且团队里只有我会说中文，所以请使用英语方便沟通。

**Comment by HollowMan6** [comment] 2023-10-20 10:02
> Hello, when I used Huawei vrglass to use the latest version 1.5wolvic, I found that the handle was not displayed, and the following input boxes and function options could not be displayed. I think it is necessary for me to report this error, and I hope the engineer can fix the problem I reported. Thank you for your hard work in developing this software and the software in China. Thank you again for your efforts!I sent it to my phone-------- 原始邮件 --------发件人： Hollow Man ***@***.***>日期： 2023年10月10日周二 16:51收件人： Igalia/wolvic ***@***.***>抄送： bizhou78 ***@***.***>, Author ***@***.***>主 题： Re: [Igalia/wolvic] 华为vr glass (Issue #1058) Hi. I think this is a duplicate of #1053, so let's continue our discussion there. And please use English when you open any issue/continue your discussion here. 这里是一个国际化的社区；并且团队里只有我会说中文，所以请使用英语方便沟通。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Actually, I'm not exactly sure what your problem is here as I don't use Huawei VR Glass. By saying `handle`, do you mean hand or just controller? And actually, I would suggest you next time to open a new issue for new bugs as this one is already closed, so that we can have better tracking of the problems.

Anyway, cc: @svillar @elima to see if you have any idea here.
