### ISSUE TITLE
Black-rendered elements in experiences using Wonderland engine on HVR

### ISSUE THREAD

**Issue by elima** [Igalia/wolvic#149] opened 2022-06-21 15:35 UTC
## Configuration

Wolvic version: 0.9.6, 0.9.7
Wolvic build ID: 
Hardware: HuaweiVR

## Steps to Reproduce
1. Go to https://constructarcade.com.
2. Open any game that uses the Wonderland engine (e.g, [Get off my Lawn](https://constructarcade.com/game/get-off-my-lawn/), [Archery Dungeon](https://constructarcade.com/game/archery-dungeon/)) 
3. Enter VR

## Current Behavior
Many game elements are rendered black. In case of Archery Dungeon, game is unplayable because Orcs can't be seen.

## Expected Behavior
Game elements are rendered normally.

**Comment by svillar** [comment] 2022-06-22 16:37
I think this might be an HVR issue since I cannot reproduce it in Quest2 neither using the OVR backend nor the OpenXR one.

**Comment by elima** [comment] 2022-08-29 09:52
@Squareys, you are probably aware of this already, but just in case.

**Comment by Squareys** [comment] 2022-09-04 09:48
Hey, sorry for the delay on the reply here!

We were using a lot more Texture2DArray layers than the limit that the WebGL2 API reports. We've found the issue a few months ago and _finally_ released a fix with the "Texture Streaming" feature in Wonderland Engine 0.9.0, which is able to handle the 256 layer maximum we get here.
In case this can be somehow increased on your side (i.e. using a pessimistic hard-coded limit rather than what the hardware reports), that can increase fidelity/performance, though!

Unfortunately, now it's up to the developers to update their games, we're already nudging them, though!

**Comment by svillar** [comment] 2022-09-08 08:37
I've tried Archery Dungeon with the upcoming 1.1 and the problems are still there.

**Comment by svillar** [comment] 2022-09-08 08:47
Another example coming from other issue is https://constructarcade.com/game/house-of-the-dead/

**Comment by Squareys** [comment] 2022-09-09 11:30
@svillar I have already offered @Sorskoot support for updating the game, but he's finishing up a game jam right now. Possibly will be updated to 0.9.1 by end of next week or something.

**Comment by sorskoot** [comment] 2022-09-09 11:53
The problem with House of the Dead is that I can't just do a rebuild with the newer version of Wonderland, there are some issues with the game itself atm. I need to check the other games to see if it's a straight forward update.

**Comment by svillar** [comment] 2022-09-20 11:40
So it looks like this is caused by issues in WonderlandEngine itself. Apparently the 0.9.1 version solves those issues. I'll close this as it isn't a Wolvic issue.

**Closed by svillar** 2022-09-20 11:40 UTC
Labels: bug, third party, hvr
