### ISSUE TITLE
Window's vertical position is reset after leaving an immersive experience

### ISSUE THREAD

**Issue by felipeerias** [Igalia/wolvic#483] opened 2023-02-12 07:58 UTC
## Configuration

Wolvic 1.3, Oculus Quest 2.

## Steps to Reproduce

1. look up and position the browser's window above your head
  ![com igalia wolvic-20230212-165534](https://user-images.githubusercontent.com/1412060/218299604-1a3a7397-3606-4619-ae97-4f292cc50836.jpg)
2. enter an immersive video
  ![com igalia wolvic-20230212-165542](https://user-images.githubusercontent.com/1412060/218299608-f0c012b8-d5ea-4a8c-9723-348792c4edda.jpg)
3. leave the video to go back to the browser
  ![com igalia wolvic-20230212-165547](https://user-images.githubusercontent.com/1412060/218299615-1b923930-7e40-4aab-af0e-e102aa8cbc9d.jpg)

## Current Behavior

The window is back in the horizontal position.

## Expected Behavior

The window remains in the same position where it was before the video was launched.

This issue also seems to happen with some VR experiences, like e.g. the game Iron Rails.

**Comment by svillar** [comment] 2023-02-16 09:03
I've seen this indeed, but in this case I don't think it's an OpenXR regression right? I think the same behaviour was there with the OculusVR backend

**Comment by svillar** [comment] 2023-02-16 15:52
Note that the code does that on purpouse, I am not sure why, but this comes from the FxR era. Note that this very same behaviour is present as well on the Meta browser and the Pico browser. I'm tempted to think that this is not a bug, but a common behaviour for immersive apps.

**Comment by svillar** [comment] 2023-10-04 15:37
Let's close this then as it seems it's the desired behaviour

**Closed by svillar** 2023-10-04 15:37 UTC
Labels: bug, unconfirmed
