### ISSUE TITLE
[Extensions] Unable to toggle any of the extension settings switches

### ISSUE THREAD

**Issue by DevPika** [Igalia/wolvic#392] opened 2022-12-26 03:23 UTC
## Configuration

Wolvic version: 1.2 and latest code in `main`

Hardware: Meta Quest 2

## Steps to Reproduce

1. Install any extension through Add-ons tab in Library
2. Click on installed addon to go to Add-on Options
3. Click on any of "Enabled" or "Run in private browsing"

## Current Behavior

The toggles/switches don't change, but seem to change on reopening the app

## Expected Behavior

The toggles/switches should change to show if Add-on setting change was applied or not

## Possible Solution

The [bind method which sets the switch state](https://github.com/Igalia/wolvic/blob/main/app/src/common/shared/com/igalia/wolvic/addons/views/AddonOptionsView.java#L69) gets called after each toggle, maybe this gets called before the add-on setting value has changed internally?

## Context

I encountered this issue while working on #391 . This affects all addons (not just locally installed ones)

**Comment by svillar** [comment] 2023-01-11 11:00
Hi @DevPika are you working on this, or should we take over?

BTW I can reproduce it too

**Comment by DevPika** [comment] 2023-01-12 05:34
@svillar Thanks for confirming the bug and letting me have a go at fixing it! I managed to follow and narrow down the problem to the [Switch toggle code](https://github.com/Igalia/wolvic/blob/main/app/src/common/shared/com/igalia/wolvic/ui/views/settings/SwitchSetting.java#L91) and [the bind call](https://github.com/Igalia/wolvic/blob/main/app/src/common/shared/com/igalia/wolvic/addons/views/AddonOptionsView.java#L193) after switch has been toggled, but am unable to figure out why the addon state is not updated. I dug into the enableAddon methods from [Addons](https://github.com/Igalia/wolvic/blob/main/app/src/common/shared/com/igalia/wolvic/browser/Addons.kt#L174) to the AddonManager, then [WolvicWebExtensionRuntime](https://github.com/Igalia/wolvic/blob/main/app/src/common/shared/com/igalia/wolvic/browser/components/WolvicWebExtensionRuntime.kt#L204) to [WebExtensionControllerImp](https://github.com/Igalia/wolvic/blob/main/app/src/common/gecko/com/igalia/wolvic/browser/api/impl/WebExtensionControllerImpl.java#L104) and even [GeckoWebExtension](https://github.com/Igalia/wolvic/blob/main/app/src/common/gecko/com/igalia/wolvic/browser/api/impl/GeckoWebExtension.kt#L368), but I am unable to single out the culprit. Please go ahead with fixing this bug!

**Comment by DevPika** [comment] 2023-01-12 05:38
Another possible clue is that the value gets updated on reopening the app, so is it because of some caching of the extension store / settings store / session store somewhere along the way?

**Comment by svillar** [comment] 2023-01-24 11:26
@felipeerias this is the bug I mentioned to you about switches in the extension settings

**Comment by felipeerias** [comment] 2023-01-25 13:06
This should be fixed by https://github.com/Igalia/wolvic/pull/443

The problem was that after enabling/disabling an add-on we were not propagating its new state correctly.

**Closed by felipeerias** 2023-01-25 13:06 UTC
Labels: bug
