### ISSUE TITLE
Be able to move browser up and down oculas quest

Currently can only move left to right Nd can't for instance put it in the floor or ceiling only a locked horizontal position 

### ISSUE THREAD

**Issue by bghrb** [Igalia/wolvic#379] opened 2022-12-09 01:24 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Be able to drag browser to any location in the sphere of VR

**Describe alternatives you've considered**
No ideas besides above but as comparison in windows you can make a browser window bigger smaller or lick to edges but in VR currently it's locked to only left to right in a circle

**Additional context**

**Comment by svillar** [comment] 2022-12-09 10:51
I think we can consider this as a duplicate of #99

**Closed by svillar** 2022-12-09 10:51 UTC
