### ISSUE TITLE
HVR add support for locked 2D view with 3DoF version

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#159] opened 2022-06-25 07:16 UTC
**Is your feature request related to a problem? Please describe.**

【Voices of Huawei VR Glass Users】
When watching videos (2D/3D movies) using Wolvic is an important scenario, the user usually takes a comfortable position with a comfortable neck, for example, lying on a sofa. Watch allows users to adjust the picture to any position in the field of view so they can watch the video lying down.

**Describe the solution you'd like**

Users can drag the display screen to any position.so that users can use it lying down.

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment] 2022-06-27 10:25
You can re-center the screen by a long click in the menu button of the right controller. Isn't that enough?

**Comment by matlu** [comment] 2022-10-25 22:37
This feature might also be useful when you are streaming content to an HMD and sitting in the backseat of a car. When the car is making 90 degrees turn the video should not suddenly turn out of view for the viewer as the head position has not moved but the seat you are sitting in has...

**Comment by svillar** [comment] 2022-12-09 10:50
I think we can consider this as a duplicate of #99

**Closed by svillar** 2022-12-09 10:50 UTC
Labels: enhancement
