### ISSUE TITLE
[OpenXR] When headset tracking is off, windows appear at "ground" level (Oculus)

### ISSUE THREAD

**Issue by felipeerias** [Igalia/wolvic#89] opened 2022-04-03 19:02 UTC
## Configuration

Wolvic version: 0.95
Hardware: Oculus Quest 2

## Steps to Reproduce

1. Go to `Settings > System > Headset Tracking` and turn it off. 
2. Launch Wolvic.

## Current Behavior

The application windows appear very low in the 3D world, like they are on the "ground".

Sometimes this bug also happens when the setting is ON. My suspicion is that in those cases headset tracking was not working well for some reason (e.g. when holding the headset with your hand, you might accidentally cover the cameras used for tracking).

## Expected Behavior

Windows appear at eye level.

When headset tracking is off, other applications display their windows at eye level. The main difference is that without tracking, the image does not change when you move your head/body around the room.

**Comment by javifernandez** [comment] 2023-03-07 10:51
I think it's worth reopening this issue, since the fix has been applied only to the OculusVR backend and the same issue is affecting the OpenXR backend, which is the one we have a default target now. 

Wolvic version: 1.3.1
Hardware: Oculus Quest 2
 SO Version: 49.0.0.207

**Comment by HollowMan6** [comment] 2023-07-22 21:04
@javifernandez I think this issue has already been fixed, can you confirm that?

**Comment by svillar** [comment] 2024-08-30 15:20
I can confirm that the Wolvic UI is not show at ground level. The controller position is misplaced but not a big deal

**Closed by svillar** 2024-08-30 15:20 UTC
Labels: bug
