### ISSUE TITLE
No picture when playing the video on with.in

### ISSUE THREAD

**Issue by lcgao** [Igalia/wolvic#261] opened 2022-09-09 13:40 UTC
## Configuration

Wolvic version: main branch
Wolvic build ID: main branch

Hardware: Mobile phone

## Steps to Reproduce

1. Access the link: https://www.with.in/watch/breathe-peace-world?autoplay=true
2. Click the 'play' icon-button to play the video.

## Current Behavior

There is the sound but NO picture.
## Expected Behavior

Not only the sound but also the picture.
## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-09-13 16:36
That experience is using WebVR. We don't support WebVR as it's a deprecated API.

**Comment by lcgao** [comment] 2022-09-14 01:31
So it doesn't work even I enable the `dom.vr.enabled` in fxr_config.yaml.

**Comment by svillar** [comment] 2022-09-14 15:05
> So it doesn't work even I enable the `dom.vr.enabled` in fxr_config.yaml.

I guess you can at least enter the session.

So if I understand it correctly the thing that does not work (even in 2D mode) is that the video is not played? If that's the case then we should take a look because WebVR has nothing to do with that then...

**Comment by lcgao** [comment] 2022-09-15 01:26
I can enter the VR session. 

Yes correct, there is no picture but sound when playing the video even if in 2D mode.

**Comment by mikemucc** [comment] 2022-09-27 18:05
I can reproduce the exact same issue on Oculus Quest 2 with Wolvic 1.1. It is acting like it's missing a codec to play the video. Is it possible some video codecs were somehow not included in the release build?

**Comment by svillar** [comment] 2022-10-11 16:42
I've just verified that this is a Gecko issue as it's also happening if Firefox for Android. [Reported](https://github.com/mozilla-mobile/fenix/issues/27371) the issue there. We can close this in Wolvic.

**Closed by svillar** 2022-10-11 16:42 UTC

**Comment by mikemucc** [comment] 2023-01-22 17:09
Is anybody following this on bugzilla... looks like no movement in months, and I'd really like to see this fixed.

**Comment by svillar** [comment] 2023-01-23 10:08
Same as #370 and #380 this will be fixed in the next version of Wolvic, after a patch that we landed in our Gecko version.
