### ISSUE TITLE
Please add support for pico3 controller.

### ISSUE THREAD

**Issue by luyangtop** [Igalia/wolvic#557] opened 2023-03-16 01:12 UTC
Please add support for pico3 controller.Pico3 can run wolvic normally, after entering the interface, it cannot interact because no pico3 controller support has been added.

**Comment by svillar** [comment] 2023-03-16 08:56
This has been requested many times like in #549. Our team has scarce resources and we cannot support any hardware out there specially if there is no partner financing that effort.

That said, given the large user base of Pico Neo3, we might consider doing that in the future.

**Comment by schaefd** [comment] 2023-04-24 22:14
Hi there- I'd also really love to see progress on this issue. With the most recent system update of the Pico OS, Firefox Reality doesn't load which really means the Pico Browser is the only option. 
I'm going to see if I can figure out how to add Pico 3 controller support.

**Comment by svillar** [comment] 2023-04-25 07:50
> Hi there- I'd also really love to see progress on this issue. With the most recent system update of the Pico OS, Firefox Reality doesn't load which really means the Pico Browser is the only option. I'm going to see if I can figure out how to add Pico 3 controller support.

It's actually pretty simple, you can see other examples in the commit log like https://github.com/Igalia/wolvic/commit/9b319b0f061ebc9a693b5064953569a9f78a0d99. Basically adding the 3D assests, a new device type and the input mappings for the controller.

**Comment by schaefd** [comment] 2023-04-25 13:25
Thanks! 
Looking at the source, the PicoNeo3 looks like its all there. There's 3D assets, devicetype, etc. I don't see the uncompressed _asset for Pico neo 3. Hmm... I'll have it dig further.

**Comment by svillar** [comment] 2023-04-25 15:49
> Thanks! Looking at the source, the PicoNeo3 looks like its all there. There's 3D assets, devicetype, etc. I don't see the uncompressed _asset for Pico neo 3. Hmm... I'll have it dig further.

The problem is that none of us have a PicoNeo3 at the moment, so we cannot release official packages without testing it first even if the work is done. Anyway I don't want to discourage you, let's see what we can do.

**Comment by schaefd** [comment] 2023-04-26 13:33
That makes sense! 
I'm going to see if I can get a build up and running. AS was throwing a bunch of errors when I did the initial setup and build. 
I just need to slow down and get things setup properly.
Anyhow, thanks for your time!

**Comment by Caio23364** [comment] 2023-06-16 22:15
I have the same problem, please add support 🥺

I'm on firmware 5.6.3 global

**Comment by DZenker** [comment] 2023-07-05 07:44
I am facing the same problems with my Pico Neo 3 pro, too.
Since the Pico 3 is used quite often in the academic and business sector (at least in Germany), controller support would be desirable. Apart from the rather bad Pico browser, there are unfortunately no alternatives on this device...

**Comment by svillar** [comment] 2023-07-05 21:20
> I am facing the same problems with my Pico Neo 3 pro, too. Since the Pico 3 is used quite often in the academic and business sector (at least in Germany), controller support would be desirable. Apart from the rather bad Pico browser, there are unfortunately no alternatives on this device...

It would be awesome if an interested partner could invest on that. Due to the size of our team we cannot prioritize this over the interests of our current partners.

**Comment by svillar** [comment] 2023-10-27 07:41
They were not merged because they were not completely correct. We plan to add support for the 3 but you have to understand that we need to prioritize the needs of our current partners and unfortunately Pico is not one of them. Stay tuned because it'll be eventually added.

**Comment by willguest** [comment] 2023-10-27 09:47
What was wrong with it? You said "I just have a suggestion for an enhancement, but if you don't want to do it I'll be happy to merge as is, just let me know", but didn't specify the problem, and then later the relevant branch was simply deleted.

It seems like CtrlBrk put effort into solving it, did so successfully, but you later found an (unspecified) issue and put the brakes on. abandoning normal feedback and revision processes. Almost all code ever written is "not completely correct". This is why git exists.

My reading between the lines says you will actively block support for this headset until you are explicitely paid to add it. Please prove me wrong.

**Comment by svillar** [comment] 2023-10-27 15:39
And BTW, if you were careful enough you'd have realized that CtrlBreak was the one abandoning #902 because as he explained in #937 he messed it up while uploading new versions of the patch. Read the conversation in that other PR which is the most recent one.

**Comment by willguest** [comment] 2023-10-27 16:07
I'm sorry you don't like the tone, but I think you read a little too much into my words.

#902 has no reference to #937 and I was not aware of this connection. It does add some context, but not much.

I also do not have information about your work schedule not do I wish to insinuate anything. I was direct in saying that it seems like you put the brakes on, which in fact was the case. You had a reason for doing so which, again, I was not aware of. 

Git is for collaboration and I did not suggest that CtrlBrk's code was intentionally buggy. You yourself say in #937 that everyone makes adjustments, so I'm not sure why you take issue with this.

The reason for my interpretation of the blocking, which was clearly marked as such, was that you provide a salesman-style justification for the lack of action on #902. Your insinuation was that, with funding from this partner, the issue would be resolved. I am not making a huge leap in saying that it won't happen until then.

As I said, happy to be wrong. Thank you for the clarification.

**Comment by svillar** [comment] 2023-10-30 09:22
> The reason for my interpretation of the blocking, which was clearly marked as such, was that you provide a salesman-style justification for the lack of action on #902. Your insinuation was that, with funding from this partner, the issue would be resolved. I am not making a huge leap in saying that it won't happen until then.

I was not really insinuating that. What I meant with that "salesman-style justification" is that we're a small team, we have limited resources and tons of things to do. Then as you could understand we need to prioritize what we spend our time on. This means that we need to give a higher priority to the issues that are important/critical for our partners because after all, they pay for those developments. We still have the control of the project but again, we need to prioritize because resources are not infinite.

Thanks for your understanding and excuse my a little bit too heated previous comment (I was really upset to receive those insinuations after devoting so much work to the Pico port that was precisely just done for the good of users).

**Comment by willguest** [comment] 2023-10-30 10:43
I do not mind at all that you responded the way you did; I was quite provocative and deserved an earful.

My interest is in getting it working. I mentioned in my first post that I was looking at trying to build an apk. Knowing where CtrlBrk got to is helpful, because it helps to gauge how hard it would be to solve. I don't really have experience with Java or C++, but the solution seems tantalisingly close and not super-tricky to solve (famous last words). 

Looking at the setup instructions, I have a couple questions:

- the Pico OpenXR SDK seems to be no longer called "mobile" and I would probably for v.1.1 - is this correct?
- as I'm not very familiar with the languages, could you give me a pointer to the files that would need changing for the interstitial widget?
- as far as testing goes, would a pre-specific video of working functionality be sufficient for a merge? I'm thinking how to get this operational as quickly as is reasonable.

I don't wish to give you extra work. Quite the opposite. With a couple of pointers, I might be able to muddle my way to a solution, but I want to make sure it's possible and makes sense in the context of your work, as I am also quite busy.

**Closed** 2024-01-25 11:15 UTC
Labels: enhancement
