### ISSUE TITLE
UI is blurry / pixelated

### ISSUE THREAD

**Issue by MrAnders0n42** [Igalia/wolvic#98] opened 2022-04-17 16:51 UTC
## Configuration

Wolvic version: 0.9.5 
Wolvic build ID: 

Hardware: Quest 2

## Steps to Reproduce

1. start Wolvic
2. look at the UI
3.

## Current Behavior

This has been an issue in FireFox Reality since I got my Quest 2 two years ago. The UI has always looked under-pixelated and none of the settings in Display make it look good. The DPI setting (which in theory should fix the problem) doesn't do anything at all. For a VR app, this is very off-putting!

## Expected Behavior

The UI should be crystal clear

## Possible Solution

Inrease the resolution / pixel density of the UI

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-05-10 12:05
Thanks for reporting. I'd be nice if you could provide some screenshot showcasing the issue you mention.

We could indeed tweak some parameters for pixel density but at the cost of memory usage. But first we need to evaluate the severity of the problem.

**Comment by MrAnders0n42** [comment] 2022-05-14 15:45
I took some screenshots but because the Quest’s screenshots resolution is low, the issue isn’t very clear.

Anyways, I’ve attached the screenshots. I took one of YouTube on the Quest browser and another in Wolvic. There’s a notable difference in YouTube’s UI (e.g Home, Explore, etc. buttons) sharpness between the two.

I also took screenshots of Wolvic’s UI. On my headset, there’s a kind of discolouration around text but that doesn’t show in screenshots. Disabling MSAA helps with this issue at the cost of overall sharpness.

I think FireFox was developed when headsets had much lower resolution, so there was no need to waste any resources on high-resolution graphics, but that’s not the case anymore. The screenshots don’t exactly reflect the real experience, and I believe visuals are essential to any VR experience. So I really hope that the “Display DPI” setting gets fixed so users could make their choice regarding performance vs. visual.

Thank you for not letting FireFox and carrying on with the development.

Best

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by svillar** [comment] 2022-05-16 11:06
Where did you upload the screenshots?

In any case, and just to clarify. You mention know blurriness in Youtube's UI. This means that you're referring to the Web content. From the initial report it looked like you're talking about the Wolvic's UI, i.e, URL bar, keyboard, settings dialog, etc...

If the issue is with the Web and WebXR content then you're probably referring to issue #111? We're releasing a new version soon, also for Oculus, which will include a patch for this. If that's the case then we can mark this a duplicate of the aforementioned one.

**Comment by svillar** [comment] 2022-07-29 17:25
I'm closing this as we didn't get any further info from the reporter in more than 2 months.

Please reopen this if you think this is still an issue. Thanks!

**Closed by svillar** 2022-07-29 17:25 UTC
Labels: question
