### ISSUE TITLE
Firefox Accounts authentication breaks if you navigate to another page

### ISSUE THREAD

**Issue by felipeerias** [Igalia/wolvic#214] opened 2022-07-26 11:15 UTC
## Configuration

Wolvic version: 1.0
Wolvic build ID: b7b87f79 (ac 63.0.0)
Hardware: Oculus Quest 2

## Steps to Reproduce

1. Launch Wolvic
2. Open `Settings`
3. Click `Sign Into Account`
4. Wolvic navigates to `accounts.firefox.com`
5. Click the Home button
6. Wolvic navigates to `wolvic.com`
7. Open `Settings` again
8. Click `Sign Into Account`

## Current Behavior

Wolvic does **not** navigate anywhere. The user can not log it to their Firefox account.

## Expected Behavior

Wolvic navigates again to `accounts.firefox.com`

## Error Logs

When the bug happens, these two lines appear in the log:

```
com.igalia.wolvic W/FirefoxAccountStateMachine: 
        Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$BeginEmailFlow@afa0651' 
        for state Active(progressState=BeginningAuthentication).

com.igalia.wolvic W/FirefoxAccountStateMachine: 
        Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Logout@b6155d2' 
        for state Active(progressState=BeginningAuthentication).
```

**Comment by svillar** [comment] 2022-07-26 12:23
Yeah I was planning to report it as I experienced the same.

**Comment by HollowMan6** [comment] 2023-07-16 12:04
I think this should have already been fixed. I can't reproduce it in the latest version. @felipeerias @svillar

**Comment by svillar** [comment] 2023-07-20 09:03
OK let's close it then...

**Closed by svillar** 2023-07-20 09:03 UTC
Labels: bug, good first issue
