### ISSUE TITLE
open a vr game，but Enter the giant screen mode instead of the VR mode.

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#30] opened 2022-02-10 08:46 UTC
## Configuration

Wolvic version: 0.9.3
Wolvic build ID: 

Hardware:  huawei vr glass 6dof

## Steps to Reproduce

1. open wolvic
2. open a 6dof game and click to enter VR mode ： moon rider
3. VR Mode runs OK
4.  press the "home" button of the right controller，enter the huawei vr glass launcher
5. open wolvic  again, wolvic run gain
6. open a vr game(moon rider)，but Enter the giant screen mode instead of the VR mode.

## Current Behavior

Enter the giant screen mode instead of the VR mode.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by fwei-io** [comment] 2022-02-10 22:15
![image](https://user-images.githubusercontent.com/57159719/153505789-1737213e-27cf-4842-a12a-ba98411dc6c9.png)
Screenshot show Moonrider cannot enter immersive mode.

**Comment by svillar** [comment] 2022-03-01 17:57
Looks like the problem is that the XR session is not properly shut down. I'd bet the handling of the "home button click" in Wolvic should be revisited

**Comment by svillar** [comment] 2022-06-14 08:00
After debugging for a while I have to say that this is again a Gecko bug. By inspecting Gecko's initialization, it turns out that it declares that the VR hardware does not support immersive sessions, and thus it does not open the page in immersive mode. I'll research a bit more in order to know whether we could easily fix it in Gecko's side.

**Comment by svillar** [comment] 2022-06-14 15:33
In the end it was not a Gecko bug. We were setting the external context of GeckoView too late. In some cases, as in the one described in this report, we were issuing `loadUri()` calls to Gecko before setting the external context. The API docs are clear on that regard, setting the external context must be done **before** loading Gecko. I've uploaded pull #145 to fix this.

**Comment by svillar** [comment] 2022-06-15 18:11
Patch landed. Expect a fix in the next release

**Closed by svillar** 2022-06-15 18:11 UTC
Labels: bug, priority-medium
