### ISSUE TITLE
acess www.baidu.com , or click “设置”-> “隐私与安全”->权限-> 位置 ， click to “允许”，the wolvic restart again and again, Into an infinite loop!

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#133] opened 2022-05-30 03:52 UTC
## Configuration

Wolvic version: https://github.com/hms-ecosystem/OpenXR-SDK/tree/main/demos/Newest_version_Igalia
Wolvic build ID: 

Hardware:  huawei vr glass 3dof/6dof

## Steps to Reproduce

one way:
1. install wolvic， open wolvic in huawei vr glass@3dof
2. type the www.baidu.com url tool bar, and enter 
3. there is a  windows  box is displayed to remind you to obtain location information.

another way to reproduce
1，open wolvic 3dof，
2、 click the toolbar，click  “设置”
3、click “隐私与安全”
4、click 权限- 位置 ， click to “允许”

then it will goto a infinite loop

## Current Behavior

here is two options click agree or not; 
if you click agree ,the wolvic restart again and again.Into an infinite loop!
details
1，access www.baidu.com website, 
2、it will push a window to  remind you"您是否要允许 m.baidu.com 获取您的位置" , agree or not，then click "agree"
3、 another push window again to remind you "是否允许 wolvic（3dof）获取此设备的位置信息"，and click “仅使用期间允许”
4、 wolvic exit，restart automatic；
5、it will goto step2 again，and into a loop 2-5.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-05-31 16:21
I've reproduced it. This **does not** happen with Oculus for example. The problem is that in the HVR case there is a system dialog that appears after granting permission. That system dialog kills Wolvic so the application is restarted. And then we get the Wolvic dialog again.

Most likely the problem is that Wolvic does not have time to store the location permission before it gets killed.

**Comment by svillar** [comment] 2022-06-24 15:27
So I found the rationale of this bug. It's basically the same problem as issue #49, we were not properly handling those situations in which the system wanted to temporarily hide Wolvic UI in order to show a dialog, or when exiting the security zone.

We used to destroy all the resources and exit whenever we were receiving onSurfaceDestroyed, but instead we should just stop the OpenXR session and recreate the Surface and kick the render loop when the application is resumed.

**Comment by svillar** [comment] 2022-06-24 15:53
This will be fixed by PR #158

**Comment by svillar** [comment] 2022-07-25 11:31
Also #189 will improve this

**Comment by svillar** [comment] 2022-10-11 11:02
Will be finally fixed by #290

**Comment by svillar** [comment] 2022-10-17 10:53
After landing it, I'm closing this

**Closed by svillar** 2022-10-17 10:53 UTC
Labels: bug, hvr
