### ISSUE TITLE
Degradation of webXR after the latest update of Oculus Quest 2 firmware

### ISSUE THREAD

**Issue by freamadmin** [Igalia/wolvic#237] opened 2022-08-12 12:27 UTC
Hi all,

we're developing a platform for multimedia VR presentations/tours, https://evryplace.com. Our virtual tours support VR mode via Web XR device APIs.

Our presentations work very well on Oculus Browser, but we've been working to ship to the client a bunch of Quest 2's with customized Wolvic browser preinstalled, because:
- we can change the background, 
- we're able to customize the build (hide some browser UI)
- and we are able to set the home page. 
All that to make a more app-like experience. Finally, we're able to autostart the app in the kiosk mode with i.e. ManageXR. 

We have tested Evryplace presentations on Wolvic 1.0.1, as well as on our custom-built Wolvic (built from main branch, with local substitution of Gecko built from wolvic-release branch) 

Evrything worked great, comparable to Oculus Quest browser (perhaps except the anti-aliasing which is much better on Oculus Browser, but we considered it a minor issue). Until wednesday morning.

We have decided to update our Quest 2s, since an update has become available - now the version is 37314400736000000. 

Suddenly, the quality of Wolvic 1.0.1 has become unacceptable in immersive VR mode. As long as the normal 'browser' mode works as it used to, when you enter immersive VR, all animations are broken, there's a lot of flickering of animated elements, also rendering of the background photospheres is sluggish, so that you see large black patches as you turn your head quickly.

We have recorded a video showing that: https://drive.google.com/file/d/1cyY-GCzPaaTvttXcGXQxoZTsTBFKb0UK/view

None of the above problems occur on the Oculus Browser: https://drive.google.com/file/d/1GFzvs7_DNq4NrDHRS57kX_0Tn2GNteF4/view

## Configuration

Wolvic version: 1.0.1
Wolvic build ID: 9baee63c (AC 63.0.0)

Hardware: Quest 2

## Steps to Reproduce
1. open https://evryplace.com/p/dzrawj
2. enter vr mode with a small VR icon in the right part of the bottom bar 
3. you will see the glitches, badly timed animations etc.

Can anybody share a similar experience? We're not sure what may have happened in the first place. I believe, this must be a Gecko issue - is there any other branch of Gecko that we could build to try to restore the way our app worked on Wolvic?

Best regards
Greg

**Comment by freamadmin** [comment] 2022-08-12 12:48
I checked some other WebXR apps to see if there is a similar degradation, thinking that perhaps it's our code's issue. 
And, as much as simple demos work fine in Wolvic even after the last update, you can see a significant difference between Wolvic and Oculus Browser i.e. on https://aframe.io/a-painter/

**Comment by svillar** [comment] 2022-08-12 15:28
First of all thanks for considering Wolvic for your project/business. Second, I encourage you folks to contribute whatever improvements/patches you think could be interesting for Wolvic as a project. For example kiosk mode sounds interesting (although we're already working on that, we might share ideas)

Now, just to be sure about the report. You mean that Wolvic 1.0.1 was working fine and then after updating the firmware of Quest2 the experience degraded a lot? If you haven't changed the Wolvic version then I guess it must be some regression added by the Meta folks. But we can double check what's going on indeed.

My Quest2 has a previous firmware version, something `35444...` and I do see the flickering in controls. For us it'll be important to know which combination of firmware + Wolvic version was working fine for you. In any case I doubt it's a regression caused by a change in Gecko. We haven't changed the Gecko version since the 0.9.x series. We are planning an update for next weeks, but after testing it again with a more recent Gecko version I still see the same issues. 

PS: wrt antialiasing, note that by default in Oculus platform we do 2x antialiasing just to be safe (we observed significant performance hits when using 4x in some experiences). You could try to change the settings to 4x to check whether the quality is similar (while keeping a good performance).

**Comment by freamadmin** [comment] 2022-08-17 06:27
Hi svillar, first of all, thanks for your support, hopefully we'll be able to find out what's going on.

So, to give you a bit of a background - we have been working on Evryplace for over 3 years now, at first it was based on the older versions of ThreeJS (with WebVR apis), then we have migrated it to the recent versions, supporting WebXR. Our reference browser for VR has always been the Oculus Browser, but last year we got interested in Firefox Reality, which then became Wolvic.

From the very beginning, Firefox Reality gave us some problems compared to Oculus Browser, (i.e. playback of video clips, or some artifacts in rendering in VR mode) but in general, it was generally acceptable. 

Recently, (especially after the release of Wolvic 1.0) we got to the point, where the Evryplace worked just great in the VR mode of Wolvic. I cannot tell you what was the version, but as far as I know, Quest updates itself automatically, and we used it heavily in June, so it would still have to be quite a recent version.

Now, it works horribly but ONLY when you switch to immersive VR mode. What is the strangest, is that the whole 3D scene is not anyhow modified upon transition to immersive VR, but suddenly both head tracking stops working right (the scene is shaking, even if you keep your head still) the time-based behaviours break (animations are way too fast), controls practically stop working, and the performance drops significantly.

I suspect, that perhaps the app is flooded with some events, that it is trying to process, and this causes all the problems? I attach a fragment from logs from our custom build of Wolvic, perhaps you can take a look at them and see something that could point us to where the problem is? This part, for example, is something that looks suspicious:

```
2022-08-16 16:49:01.270 1641-14796/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1057 android.content.ContextWrapper.sendBroadcast:448 X.oF.A00:143 X.oD.A00:17 X.oD.handleMessage:90 
2022-08-16 16:49:01.281 14495-14631/com.igalia.wolvic.fream W/Web Content: [JavaScript Warning: "WebGL warning: clear: Framebuffer must be complete." {file: "https://hir.fre.am/player/evr.min.js" line: 6}]
2022-08-16 16:49:01.291 14495-14631/com.igalia.wolvic.fream W/Web Content: [JavaScript Warning: "WebGL warning: drawArraysInstanced: Framebuffer must be complete." {file: "https://hir.fre.am/player/evr.min.js" line: 6}]
2022-08-16 16:49:01.292 14495-14631/com.igalia.wolvic.fream W/Web Content: [JavaScript Warning: "WebGL warning: drawArraysInstanced: Framebuffer must be complete." {file: "https://hir.fre.am/player/evr.min.js" line: 6}]
2022-08-16 16:49:01.301 14495-14631/com.igalia.wolvic.fream W/Web Content: [JavaScript Warning: "WebGL warning: drawElementsInstanced: Framebuffer must be complete." {file: "https://hir.fre.am/player/evr.min.js" line: 6}]
2022-08-16 16:49:01.351 14495-14631/com.igalia.wolvic.fream I/chatty: uid=10085(com.igalia.wolvic.fream) Web Content identical 27 lines
2022-08-16 16:49:01.352 14495-14631/com.igalia.wolvic.fream W/Web Content: [JavaScript Warning: "WebGL warning: drawElementsInstanced: Framebuffer must be complete." {file: "https://hir.fre.am/player/evr.min.js" line: 6}]
2022-08-16 16:49:01.352 14495-14631/com.igalia.wolvic.fream W/Web Content: [JavaScript Warning: "After reporting 32, no further warnings will be reported for this WebGL context." {file: "https://hir.fre.am/player/evr.min.js" line: 6}]
```

I would be very grateful for help, we are hoping to resolve this issue by the end of the month, because we need to deliver the working version of our app.
[oculus log.txt](https://github.com/Igalia/wolvic/files/9356918/oculus.log.txt)


Best regards
Greg

**Comment by freamadmin** [comment] 2022-08-17 23:01
Hi Svillar, 

I have a quick update. In the first message, I gave you the OS version code that my headset got after the update, 37314400736000000. The Oculus version that corresponds to it is 43.0.0.167.120.387708431. That actually is the most recent update of the Quest 2.

It did not get a good press. People report apps breaking, mostly the Oculus Link.
https://forums.oculusvr.com/t5/Announcements-and-Releases/PTC-v43-Release-Megathread/td-p/974676

I'm now 100% positive that v42.xxx was the Quest 2 version on which I had the most positive experience with my webxr content in Wolvic.

Hopefully they're working on a fix.
Regards
Greg

**Comment by svillar** [comment] 2022-09-26 14:27
Anything new wrt this issue?

**Comment by svillar** [comment] 2022-10-11 16:44
No new from reporter in 2 months. I'm closing this then. Please do reopen if you are able to still reproduce issue or just in case you have additional data that could allow us to investigate the issue.

**Closed by svillar** 2022-10-11 16:44 UTC
