### ISSUE TITLE
fullscreen video no sound when there's two windows

### ISSUE THREAD

**Issue by ethaniel86** [Igalia/wolvic#1332] opened 2024-04-01 04:19 UTC
## Configuration

Wolvic version: 1.6
Wolvic build ID: b64e81e8

Hardware: Meta Quest 3

## Steps to Reproduce
1. open two windows
2. launch any videos in full screen on either one window
3. the playing video has no sound, no issue when exit full screen

## Current Behavior
no sound when playing full screen video, when two(or probably more) windows opened

## Expected Behavior
got sound when playing full screen video, with multiple windows opened

```
```

</details>

**Comment by svillar** [comment] 2024-04-01 07:39
Thanks for reporting? Is there any other media playing in the other windows?

**Comment by ethaniel86** [comment] 2024-04-01 07:48
don't think so. I have done another test see below screenshot.
Left window - Google search
Right window - Youtube playing video no issue. When going full screen the video got no sound. 

![image](https://github.com/Igalia/wolvic/assets/11464581/eb973b30-7370-410a-a2b5-6856c8fb5bd9)

**Comment by svillar** [comment] 2024-04-03 10:10
I have tested this and I am not able to reproduce it. I have sound both in fullscreen and in window mode. I recorded a video but I got no sound in the recording. Will tray with some other tool.

**Comment by ethaniel86** [comment] 2024-04-03 13:27
Oh well I'm unable to reproduce the issue since device restarted. 
In case it happens again will the "enable debug" under developer settings useful for troubleshooting?

**Comment by svillar** [comment] 2024-04-04 16:04
> Oh well I'm unable to reproduce the issue since device restarted. In case it happens again will the "enable debug" under developer settings useful for troubleshooting?

not really, that's for inspecting web pages using a desktop browser. I'll close this now, please reopen if you're able to reproduce it again. Thanks!

**Closed by svillar** 2024-04-04 16:04 UTC
Labels: bug, unconfirmed
