### ISSUE TITLE
XR video not showing

### ISSUE THREAD

**Issue by SpaceArchitecture** [Igalia/wolvic#370] opened 2022-12-05 02:29 UTC
## Configuration

Wolvic version: 1.2
Wolvic build ID: 

Hardware: Quest 2

## Steps to Reproduce

1. Click on XR video play content
2. Wait
3. Nothing

## Current Behavior

Black screen with controls 

## Expected Behavior

Video playing with controls

## Possible Solution

Who knows, it worked meeehhh in firefox

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-12-05 09:02
We'd need more data. Which video is not working?

**Comment by SpaceArchitecture** [comment] 2022-12-07 05:08
Most, try it yourself

**Comment by svillar** [comment] 2022-12-07 12:40
> Most, try it yourself

If I ask is because videos work fine for me. But "videos" is a pretty generic term, what are you referring too, locally stored videos?, YouTube videos?, Vimeo videos?. Also which format, "normal" 2D, 360, there are tons of combinations.

It's enough if you paste here a couple of URLs of videos that do not work for you

**Comment by svillar** [comment] 2022-12-14 16:00
@SpaceArchitecture it'd be awesome if you could give us more data. We got some reports of video not working but we're unable to reproduce the issue, so any help would be highly appreciated. Thanks!

**Comment by nfswissue** [comment] 2022-12-22 13:22
I had same issue on NSFW sites. Shall I mention them? (Not sure if against terms of use for this site) Video doesn't work but audio works. Couple of device restarts later if lucky video also works.

**Comment by nfswissue** [comment] 2022-12-22 14:12
In case it's not. It was multiple NSFW vr sites. PHub, PHub Premium, vrcosplayx.com, vrphub.com

**Comment by SpaceArchitecture** [comment] 2022-12-28 19:50
Yup, I am not saying the same with me but probably

**Comment by tech42676** [comment] 2023-01-09 16:11
Same problem.

**Comment by svillar** [comment] 2023-01-09 18:29
> In case it's not. It was multiple NSFW vr sites. PHub, PHub Premium, vrcosplayx.com, vrphub.com

Thanks, that helps a lot

**Comment by svillar** [comment] 2023-01-09 20:32
> > In case it's not. It was multiple NSFW vr sites. PHub, PHub Premium, vrcosplayx.com, vrphub.com
> 
> Thanks, that helps a lot

BTW when did it started to happen, in 1.2 ? 1.1 ?

We updated the Gecko version in 1.1, so maybe that is the culprit

**Comment by nfswissue** [comment] 2023-01-09 23:47
I haven't used 1.1 so can't help you there sorry.

**Comment by bkardell** [comment] 2023-01-17 18:20
It does seem that any video using the popular dl8 player is having this problem and it seems that's quite a long list of sites.  Builtwith gave me some https://trends.builtwith.com/websitelist/Delight-XR, but that is an incomplete list for sure.  

Checking a few of those with a remote debugger I do see a number of errors logged, the GL ones below are unique to Wolvic on the Quest, as far as I can tell (that is, they don't happen in FF on the desktop, for example)

```
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:53:21608
2157 e No DPDB device match. dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:51:22773
2157 e Failed to recalculate device parameters. dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:51:22773
XRWebGLLayer doesn't support no alpha value. Alpha will be enabled. dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:52:30120
XRWebGLLayer doesn't support separate depth or stencil buffers. They will be enabled together. dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:52:30120
Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request. 0.dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:18
WebGL warning: tex(Sub)Image[23]D: Failed to retrieve source bytes for CPU upload. dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:16:533
WebGL warning: tex(Sub)Image[23]D: Failed to retrieve source bytes for CPU upload. 31 dl8-1669c3b53e90a9b79e31abcf19b95e97768fe4b4.js:16:27096
After reporting 32, no further warnings will be reported for this WebGL context.
```

It seems FFR itself had a problem with this in 2019 https://github.com/MozillaReality/FirefoxReality/issues/1212 and then almost exactly the issue as described/experienced in 2020 too https://github.com/MozillaReality/FirefoxReality/issues/3301

In any case https://www.mindvr.com/videos/?v=ccltbn is at least one suitable for work URL that can be used to debug and exhibited similar for me

**Comment by svillar** [comment] 2023-01-18 18:08
We have good news :tada: There is a patch for the [Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1655101) that once applied to our Gecko fork makes videos work again. Will be part of the upcoming 1.3 release.

**Closed by svillar** 2023-01-18 18:08 UTC
Labels: bug, question
