### ISSUE TITLE
Bug with WebXR Hands input profile

### ISSUE THREAD

**Issue by De-Panther** [Igalia/wolvic#481] opened 2023-02-11 01:11 UTC
## Configuration

Wolvic version: 1.3 (versionCode 70)
Wolvic build ID: dc050672 (AC 7 5.0.22)

Hardware: Oculus Quest 1. OS 49.

## Steps to Reproduce

1. Enter https://immersive-web.github.io/webxr-samples/controller-state.html
2. Enter VR.
3. Use Hands instead of controllers.
4. The models that represents the hands are the Touch Controllers, instead of Hand model.

## Current Behavior

Instead of displaying Hands models for the hands, it shows the models of the device controllers.

## Expected Behavior

It should display the Hands models, using the hands input profile.

## Possible Solution

Report on a correct Input Profile in the controller input source for hands. (`XRSession.inputSources` and `XRSession` `inputsourceschange` event)
https://github.com/immersive-web/webxr-input-profiles

## Context

I'm implementing WebXR Export option in Unity, and it affects experiences and demos using this extension.
Demo: https://de-panther.github.io/unity-webxr-export/Build/
In the demo it loads white hands models based on the correct WebXR Input Profile, and the model joints are changing according to the user fingers.
When not using the Input Profiles, the demo should display boxes where the hands joints are.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by msub2** [comment] 2023-02-11 02:05
I don't believe there's any support for the WebXR Hand Tracking module, given that Wolvic is still shipping with GeckoView. I would imagine since the hand tracking is OpenXR-based it'd probably only function with Chromium or Webkit right now.

**Comment by De-Panther** [comment] 2023-02-11 02:17
As they added support for Hands in the menus, they do have the tracking data of the hands.
As a user, I don't expect to see the controllers of the device when I'm using hand tracking. So I think that event if they currently not supporting the WebXR Hands Module with the joints, at least they should report on another Input Profile.

**Comment by msub2** [comment] 2023-02-11 02:25
That's fair yeah. I guess if joints weren't a hard requirement, they could get it into Gecko by adding the hands profile to the VRControllerType enum in `gfx/vr/moz_external_vr.h` and then adding a case for it in `dom/vr/XRInputSource.cpp` so it at least reports correctly (although you'd probably need to give some indication to specifically select hands somehow, not sure about that part)

**Comment by De-Panther** [comment] 2023-02-11 02:40
I'm also not sure, if using the hands profile won't break existing experiences, as they might relay on the joints data.
Maybe if there's no support for the WebXR Hands module, it should report `generic-trigger` as the profile.

**Comment by svillar** [comment] 2023-02-11 20:26
Gecko does not implement the hands API. You can see the controllers because we emulate them so that users could enjoy WebXR experiences with hand tracking.

**Comment by Utopiah** [comment] 2023-03-01 10:47
Seems I got confused to from https://wolvic.com/blog/release_1.3/ "Another benefit of using OpenXR is that the brand new hand tracking support we’ve just added, should work on all the platforms" which works in the browser UI yet not while trying a WebXR experience e.g https://aframe.io/examples/showcase/handtracking/

**Comment by javifernandez** [comment] 2023-08-23 10:34
Tried to reproduce the issue with 1.4.2 and we have a different behavior:

I see no model at all, neither the controllers or the hands model. The hand gestures works as expected, though, showing the icons when the associated actions are activated.

**Comment by svillar** [comment] 2023-10-04 15:28
Assigning to @elima , this will be fixed in the Chromium port

**Comment by svillar** [comment] 2024-06-03 12:26
Hand tracking API is supported in Chromium backend, please check it out and reopen if there is something that needs to be fixed.

**Closed by svillar** 2024-06-03 12:26 UTC
Labels: bug

**Comment by De-Panther** [comment] 2024-06-03 12:28
Wolvic in Quest store is already using Chromiun? What version? I'll test this week

**Comment by svillar** [comment] 2024-06-03 12:30
> Wolvic in Quest store is already using Chromiun? What version? I'll test this week

Nop but you can find packages for sideloading in the [downloads page](https://wolvic.com/dl/)

**Comment by Utopiah** [comment] 2024-06-05 06:54
Neat, works well! Any chance for a Lynx build?

**Comment by HyroVitalyProtago** [comment] 2024-06-05 08:57
+1 for the Lynx build
