### ISSUE TITLE
Background of AR / MR immersive scene is black instead of passthrough on Quest 3

### ISSUE THREAD

**Issue by kierannolan** [Igalia/wolvic#1156] opened 2023-12-20 12:46 UTC
## Configuration

Wolvic version: 1.5.2
Wolvic build ID: versionCode 244

Hardware: Meta Quest 3

## Steps to Reproduce

1. Going into immersive mode in an AR scene shows a black background instead of the passthrough camera.

Here's a link to a sample scene on Glitch.me for test purposes:
[https://invincible-frost-cost.glitch.me](https://invincible-frost-cost.glitch.me)

( also code link is [here](https://glitch.com/edit/#!/invincible-frost-cost.glitch.me).)
This scene will display in passthrough AR / Mixed Reality mode on the Meta browser but not the current Wolvic Browser.

Many thanks for your help in addressing this bug.

## Current Behavior

Background is black

## Expected Behavior

Background should be completely transparent and in passthrough mode

```
```

</details>

**Comment by svillar** [comment] 2023-12-21 09:14
I gues you are using WebXR layers for that? That's currently unsupported (see #992) but we plan to work on that next year for the Chromium backend.

**Comment by kierannolan** [comment] 2023-12-21 14:08
Thank you Svillar for the update and your work on this.

**Comment by svillar** [comment] 2023-12-21 19:31
> Thank you Svillar for the update and your work on this.

You didn't ask my question? Should I assume that it's indeed using WebXR layers?

**Comment by kierannolan** [comment] 2023-12-21 20:22
I'm not certain of the underlying technology, but I think you're right.

I'm using A-Frame, here's their page on their use of WebXR and AR mode.
Hopefully it's of help:
https://aframe.io/docs/1.5.0/components/webxr.html

**Comment by svillar** [comment] 2024-01-11 20:52
If the problem is that it's using WebXRLayers (I'll try to verify) then it'll be fixed once #992 is fixed

**Comment by svillar** [comment] 2024-01-12 16:56
OK I've just checked your example and Wolvic is not missbehaving. As you can see we only offer the "VR" button because Gecko (the underlying web engine) does not support WebXR AR APIs.

In the case of the Meta browser it's based on Chromium which do support WebXR AR APIs. If you open it with the Meta browser you'd notice how you have the AR button and the VR button. If you use the VR button you'll see exactly the same black background as you see in Wolvic.

The WebXR AR support will come with the chromium based version of Wolvic that will be released this year.

Thanks for reporting!

**Closed by svillar** 2024-01-12 16:56 UTC
