### ISSUE TITLE
Immersive start page, no Wolvic UI shown

### ISSUE THREAD

**Issue by Utopiah** [Igalia/wolvic#1279] opened 2024-03-01 10:53 UTC
**Is your feature request related to a problem? Please describe.**
I do no program natively but solely on the Web, mostly WebXR. I want to skip the OS UI to go straight to Wolvic. From there I can have a start page

**Describe the solution you'd like**
Supporting it at all (if that's not already the case), then allowing it via setting option, if not as a command line option

**Describe alternatives you've considered**
- WebExtension might be sufficient, done https://github.com/Utopiah/vrify before
- adb command
- https://wiki.termux.com/wiki/Termux:Boot

**Additional context**
- B2G https://wiki.mozilla.org/Booting_to_the_Web
- rooting Lynx https://lynx.miraheze.org/wiki/Rooting_Process

**Comment by svillar** [comment] 2024-03-01 11:35
Duplicate of #1211 ?

**Comment by Utopiah** [comment] 2024-03-01 12:21
Does #1211 concerns the start page or even opening via an `adb` command/intent?

My point being not of open Wolvic then navigating to an immersive WebXR page then opening it in XR (which I believe that other issue is about) but rather starting Wolvic and have e.g https://aframe.io/aframe/examples/boilerplate/hello-world/ directly in VR.

**Comment by svillar** [comment] 2024-03-01 13:14
> Does #1211 concerns the start page or even opening via an `adb` command/intent?
> 
> My point being not of open Wolvic then navigating to an immersive WebXR page then opening it in XR (which I believe that other issue is about) but rather starting Wolvic and have e.g https://aframe.io/aframe/examples/boilerplate/hello-world/ directly in VR.

Then you're talking about https://github.com/Igalia/wolvic/pull/1171

**Comment by Utopiah** [comment] 2024-03-01 13:40
#1171 provides a very interesting way to solve this without touching much the code itself through the extension. I believe this is such a rare use case (for now) that now have a UI modified but just parameters is indeed enough.

So in my example @felipeerias would it mean

```
adb shell am start -n "com.igalia.wolvic/com.igalia.wolvic.VRBrowserActivity" \
    -a android.intent.action.MAIN                                             \
    -c android.intent.category.LAUNCHER                                       \
    -a android.intent.action.VIEW                                             \
    -d "https://aframe.io/aframe/examples/boilerplate/hello-world/"           \
    --ez open_in_immersive true                                               \
    --ez hide_webxr_interstitial true                                         \
    -e open_in_immersive_parent_xpath ''                                      \
    -e open_in_immersive_element_xpath '/html/body/a-scene/div[2]/button'
``` ?

Finally @svillar do you imagine this PR would be reviewed soon? I have it in mind for https://github.com/Igalia/wolvic/issues/1103 but as I'm building myself for now I could just pull-in this patch.

**Comment by svillar** [comment] 2024-03-06 10:58
> Finally @svillar do you imagine this PR would be reviewed soon? I have it in mind for #1103 but as I'm building myself for now I could just pull-in this patch.

Sure, somehow it got its way in the middle of my work pile and didn't have a chance to get my attention. I'll review it sooner than later

**Comment by svillar** [comment] 2024-03-15 15:41
Then I think this could be the same as #735 ?

**Comment by LAGENCECREE** [comment] 2024-04-16 12:19
just to mention, pico finaly added immersive pwa to support this kind of uses on there headsets

**Comment by LAGENCECREE** [comment] 2024-04-16 12:57
just to mention, pico finaly added immersive pwa to support this kind of vital uses on there headsets

**Comment by LAGENCECREE** [comment] 2024-04-16 12:59
partially 🧐

**Closed** 2024-10-21 07:59 UTC
Labels: enhancement
