### ISSUE TITLE
Play videos in more than one window simultaneously

### ISSUE THREAD

**Issue by Kalrkloss** [Igalia/wolvic#1260] opened 2024-02-16 11:20 UTC
**Is your feature request related to a problem? Please describe.**
While playing a video/stream in one window: when you start a video in a second window, the video in the first windows stops.

**Describe the solution you'd like**
The possibility to play more than one video at once, ideally three videos playing simultaneously in three browser windows.

**Additional context**
It happened once on my headset (Pico 4), that a video in one window kept playing when I started one in a second window, so I think limiting playback to one video at the time isn't a technical limit, but was a design choice. I wasn't able to repeat that behaviour, though.
If so, is there a place in the code where I can change that, so that more than one video can be played at the same time?

**Comment by svillar** [comment] 2024-06-03 12:20
I was not able to reproduce it. Did it happen to you more than once? If not, then maybe the problem was something else.

**Comment by svillar** [comment] 2024-08-13 11:20
> I was not able to reproduce it. Did it happen to you more than once? If not, then maybe the problem was something else.

I step back, this is actually pretty easy to reproduce

**Comment by svillar** [comment] 2024-08-13 11:21
After checking what's going on I'm closing this for two reasons:
1. this is not a limitation of Wolvic, it's actually Gecko the one pausing the session, as it does not allow two videos to be played simultaneously (Android only restriction). We just get a notification from Gecko that the video was paused
2. this works fine in the Chromium backend that does not have that limitation

**Closed by svillar** 2024-08-13 11:21 UTC
Labels: enhancement, needinfo
