### ISSUE TITLE
Builds for Spaces crashes when launching on a VRX device.

### ISSUE THREAD

**Issue by FanEric** [Igalia/wolvic#1074] opened 2023-10-20 03:50 UTC
## Configuration

Wolvic version: 1.5
Wolvic build ID: 
Spaces Service version: 0.14 & 0.17

Hardware: Lenovo VRX

## Steps to Reproduce

1. Building Gecko(version 116.0.3) following doc--success
2. Put libopenxr_loader.aar to third_party/spaces folder
3. Switch Build Variant to SpacesArm64GeckoGenericRelease
4. Build apk--success
5. Install and run apk on VRX

## Current Behavior
App crashes immediately when launching

## Expected Behavior
App runs successfully when launching

## Context
Variant SpacesArm64GeckoGenericDebug works fine

## Error Logs and Stack Traces
10-19 09:02:39.651  4388  4406 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
10-19 09:02:39.651  4388  4406 E AndroidRuntime: Process: com.igalia.wolvic:crash, PID: 4388
10-19 09:02:39.651  4388  4406 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: Caused by: java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 31 ("AsyncTask #1")
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:69)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:2)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoRuntime.create(GeckoRuntime.java:3)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at com.igalia.wolvic.browser.api.impl.RuntimeImpl.<init>(RuntimeImpl.java:298)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at com.igalia.wolvic.browser.api.WFactory.createRuntime(WFactory.java:3)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at com.igalia.wolvic.browser.engine.EngineProvider.getOrCreateRuntime(EngineProvider.kt:206)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at com.igalia.wolvic.crashreporting.CrashReporterService.onHandleWork(CrashReporterService.java:11)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:84)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-19 09:02:39.651  4388  4406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[Wolvic crash.log](https://github.com/Igalia/wolvic/files/13049752/Wolvic.crash.log)

Full log, please refer to attachment

```
```

</details>

**Comment by svillar** [comment] 2023-10-20 09:14
Works fine for me here in my VRX. Can you try to run a debug session with android studio and check when the crash happens? The exception you pasted above is just the crash reporter service which is not correctly implemented (there is a PR to fix that)

**Comment by FanEric** [comment] 2023-10-23 01:26
Thanks svillar, the debug Variant in my VRX works fine, too. The crash only happens with Release version in VRX.  And I also tried with PICO and Meta pro, both of them work fine (Release version). So It's a little wired.

**Comment by svillar** [comment] 2023-10-23 11:04
> Thanks svillar, the debug Variant in my VRX works fine, too. The crash only happens with Release version in VRX. And I also tried with PICO and it also works fine (Release version). So It's a little wired.

the main difference between debug and release is that release enables minification of java code. We have seen crashes in other architectures as well. Try to set `m̀inifyEnabled false` in the build.grade for release builds and let me know if that fixes the issue.

**Comment by FanEric** [comment] 2023-10-24 07:27
No, get the same error message...

**Comment by svillar** [comment] 2023-10-24 08:39
> No, get the same error message...

So then look for some other crash that should happen before that, because as I mentioned that crash is the consequence rather than the cause.

**Comment by svillar** [comment] 2023-11-06 16:02
Any progress on this?

**Comment by svillar** [comment] 2023-11-14 10:16
No more input after 3 weeks. I'll close this. Please reopen if the issue is still there for you.

**Closed by svillar** 2023-11-14 10:16 UTC
Labels: bug
