### ISSUE TITLE
Synchronize browsing records and bookmarks between browsers (such as Firefox and Chrome) on mobile phones or PCs and Wolvic VR.

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#117] opened 2022-05-12 07:42 UTC
**Is your feature request related to a problem? Please describe.**

here is the update of the 0.9.5 of wolvic: 
This release of Wolvic is primarily focused on a few significant updates to the browser itself:
The resoration of the sync/send tabs functionality that was previously available in Firefox Reality. You can now sync your bookmarks and send tabs between devices running Firefox and Wolvic.
-- but in the vr brower, it is very difficult to input the URL ;

**Describe the solution you'd like**
Synchronize browsing records and bookmarks between browsers (such as Firefox and Chrome) on mobile phones or PCs and Wolvic VR.
1. The same user account has been used to log in to the Firefox and Wolvic.
2. Take Firefox as an example. On a mobile phone or PC, it is convenient to enter or search for WebXR or 2D content because the keyboard is used for input. Use the Firefox browser to access a website. or have a website in favorites;
3. The user can view the historical records or favorites in Wolvic.

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment] 2022-05-13 11:03
Wolvic already synchronizes bookmarks with Firefox desktop. In the case of Chromium, Chromium does not support firefox accounts so there is little we could do there. Google has it's own synchronization sysmtem and I doubt they'd be interested in adding the firefox one.

What is exactly the feature you are requesting?

**Comment by dingsing2021** [comment] 2022-05-19 03:10
I have test the sync feature(bookmarks & histoy) between firefox android & wolvic , I am sure that I use the same account to login, but it does not work. 
the firefox  android  version that I used download from china website, maybe the server(user information) is local, and wolvic could not get the data from china server of firefox .

**Comment by matlu** [comment] 2022-05-19 18:23
Note that Firefox Account Sync is using "Domestic China Service" (which cannot be changed by the user).
It is likely using a different server than the rest of Firefox Accounts.

Please make sure you are using Firefox for Android as published in China when testing.
Firefox Accounts for China usage are created at firefox.com.cn

**Comment by svillar** [comment] 2022-05-20 09:30
I agree the problem is likely that China version is using a different server. We don't select the server for accounts synchronization, we just use a component provided by mozilla to perform the syncing. We'll investigate whether a different component exists for the China market.

**Comment by matlu** [comment] 2022-05-20 14:53
Should be fairly easy to verify as long as you use the Firefox for Android China app which is made by Mozilla China Office for the account creation.

**Comment by svillar** [comment] 2022-05-23 11:04
OK I found how to force the mozilla component to use the China server for China builds. I'll upload a PR soon.

**Comment by dingsing2021** [comment] 2022-05-26 00:18
here is the test result for newest version build at 5-24
here is something wrong from Firefox web
https://user-images.githubusercontent.com/86649949/170389879-927984dd-2aa3-4fcc-8156-99159f47a9f2.mp4

**Comment by svillar** [comment] 2022-05-26 08:09
> here is the test result for newest version build at 5-24
> here is something wrong from Firefox web
> https://user-images.githubusercontent.com/86649949/170389879-927984dd-2aa3-4fcc-8156-99159f47a9f2.mp4

Are you testing from mainland China? It might be possible that the URL is only accessible from China.

**Comment by svillar** [comment] 2022-05-26 10:27
I found the problem. We were using a client_id that allowed synchronization for everyone but China users (who use another server). I've replaced it with a different one that supports synchronization even in China. It should be fixed as part of [this PR](https://github.com/Igalia/wolvic/pull/128) and will be available in 0.9.6 release. Thanks for reporting

**Closed by svillar** 2022-05-26 10:27 UTC
Labels: bug, priority-high
