### ISSUE TITLE
instant crash quest 2 after upgrading to SO v51 

### ISSUE THREAD

**Issue by cjbigz1000** [Igalia/wolvic#606] opened 2023-04-10 02:09 UTC
## Configuration

Wolvic version: 1.3.3
Wolvic build ID: 84
Newest update April 7th 2023 

Hardware: meta quest 2
Version: 51.0.0.173.268.463372067

## Steps to Reproduce

1.
2.
3.

## Error Logs and Stack Traces

<details open>

```
```

</details>
As soon as I start the application It does not do anything, just instant crash.

**Comment by cjbigz1000** [comment] 2023-04-10 02:11
I also have reinstalled it. Still does the same.

**Comment by cjbigz1000** [comment] 2023-04-10 02:13
my bad not sure how to use github yet just trying to help fix issue

**Comment by svillar** [comment] 2023-04-10 13:59
Thanks for reporting. So which version are you trying to use, the one from the official Meta store or the one from Applab?

Another question, did you have Wolvic previously installed? Or is it a first time installation?

**Comment by cjbigz1000** [comment] 2023-04-10 14:22
Its the official and ive used it for months now and just got the new update and it is just crashing as soon as i start the app all i see is a window with a bunch of colors in it and im still at the quest home screen

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by svillar** [comment] 2023-04-10 14:29
> Its the official and ive used it for months now and just got the new update and it is just crashing as soon as i start the app all i see is a window with a bunch of colors in it and im still at the quest home screen Sent from my Verizon, Samsung Galaxy smartphone Get Outlook for Android<https://aka.ms/AAb9ysg>

Hmm so there is something that does not match. The one in the official meta store has been recently released. If you have been using it for months then I guess you're using the AppLab's version. So in order to figure out what happens we'd need some logs from the device. Do you know how to get logs from the device? Do you know how to use `adb` to get the logs from the device?

BTW as a last resource, you might want to delete all the application data in the system preferences and then try to launch Wolvic again, but that will remove all your history/bookmarks/downloads etc...

**Comment by mikemucc** [comment] 2023-04-14 20:38
I am also having this issue.

When I start Wolvic, it instantly crashes. I am running official Wolvic from the Oculus store, although I did run the AppLab version prior to this.

Sometimes, I am presented with the Quest 2 OS dialog that says "The app Wolvic keeps Crashing" with the choices of "about" and "force quit". Force Quitting returns you to the OS.

Attempting to run Wolvic again causes the Oculus UI to put a little "dot" below the Wolvic icon (like it's running) but you cannot interact with the program or force quit it again. 

Additionally, as described above (I think) you do get a blank window (the window has a gradient across it, probably generated by the OS) with only a Close (X) and Minimize (_) widget on it. Clicking Close does nothing here though except get rid of this window.

I will try the "purge" option suggested above later this evening as I have time and report back. I could potentially capture logs as well if that does not fix it.

**Comment by Odyssey346** [comment] 2023-04-14 20:39
Happens to me as well. I turned my Oculus Quest 2 on for the first time in months, went into Wolvic and saw a message telling me to reinstall it as a normal app. So I did that, and it just keeps crashing.

**Comment by mikemucc** [comment] 2023-04-15 15:21
Update: Deleting all application data in the system preferences did not fix the problem.

**Comment by javifernandez** [comment] 2023-04-17 13:21
> Update: Deleting all application data in the system preferences did **not** fix the problem.

Did you try a fresh install of the version 1.3.3  ?

**Comment by javifernandez** [comment] 2023-04-17 21:50
Could you please provide the SO version ? You can get it in the Settings > System > Software updates 

It'd be interesting to know if it's the same than the one reported in #613

Thank you very much for your feedback.

**Comment by mikemucc** [comment] 2023-04-17 22:21
OS Version:
SQ3A.220605.009.A1

Version:
51.0.0.173.268.463372067

Runtime Version 
51.0.0.173.269.463372413

System Version:
50327160085300150

**Comment by javifernandez** [comment] 2023-04-17 22:23
I'm starting to think the crashes are related to the new SO version 51.  I guess a rollback to 50 is not easy to do, but it'd help us to confirm the issue. 

Unfortunately I'm not offered an upgrade to 51 for my device.

**Comment by mikemucc** [comment] 2023-04-17 22:28
> I'm starting to think the crashes are related to the new SO version 51. I guess a rollback to 50 is not easy to do, but it'd help us to confirm the issue.

Based on the comments above about doing software updates and it stopping working (and my own experience of it literally working one day and failing the next) and the fact that we have OS version mismatches, I think you are correct.

**Comment by javifernandez** [comment] 2023-04-17 22:31
Yeah, thanks a lot. We are now on the track and we have something to work on to provide a fix for the version 51.

**Comment by javifernandez** [comment] 2023-04-17 22:34
> Yeah, thanks a lot. We are now on the track and we have something to work on to provide a fix for the version 51.
> 
> Would to mind if we close this as dup of #613 ?

Umm, perhaps we could do the opposite, since this has been filed before, but upgrading the title.

**Comment by mikemucc** [comment] 2023-04-17 22:34
I don't care, since I'm already following #613, but others who have commented may not have any way of getting the notifications?

I would almost suggest renaming this one and closing 613 as the dupe?

Too bad Github doesn't allow for merging of threads.

>Umm, perhaps we could do the opposite, since this has been filed before, but upgrading the title.

Literally showed up as I was typing the above... :-)

**Comment by javifernandez** [comment] 2023-04-17 23:33
I managed to upgrade to v51 and reproduce the issue with the Wolvic 1.3.3, as described in the bug report.

I also confirmed that the fix for #/602 solves this issue, probably because both share the same root case (if they are not just dup).

**Comment by mikemucc** [comment] 2023-04-18 18:35
So this is fixed by #609? I'd say you could close it, though you might want to leave it open until that version is released for visibility.

Any timeline on that release?

**Comment by javifernandez** [comment] 2023-04-19 09:31
> Any timeline on that release? 

I´d say in the next days. We are having some difficulties with some dependencies if the new SO when building the packages for the meta store. We have confirmed that it works when building the dev packages, so it's just a matter of solving the issues with the official packages.

Thanks again for your patient and support.

**Comment by mikemucc** [comment] 2023-04-20 21:48
You bet. Wolvic is filling a very important niche, at least on the Oculus Quest. I don't think anybody trusts Meta or their default browser to not send your entire browsing history back to Meta along with a whole bunch of other data. :-)

**Comment by svillar** [comment] 2023-04-21 08:35
So we are planning to release 1.3.4 soon with a fix for that. The thing is that I got another OS upgrade to version 53..something and 1.3.3 works fine there. Could any @mikemucc @cjbigz1000 @Odyssey346 confirm?

**Comment by mikemucc** [comment] 2023-04-21 20:21
I tried Wolvic this afternoon and was able to use it successfully. I didn't see that the OS version was changed (Still showed a v51....).

**Comment by svillar** [comment] 2023-05-04 14:11
Fixed by #609 and followups some time ago.

**Closed by svillar** 2023-05-04 14:11 UTC
Labels: priority-high
