### ISSUE TITLE
Wolvic version: 0.9.3 & SDK version 3.5.0.76 (the latest commercial version ) Mismatch，6dof controller-related issues

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#47] opened 2022-02-22 03:55 UTC
## Configuration

Wolvic version: 0.9.3
Wolvic build ID: 

Hardware:  huawei vr glass 6dof  & SDK version 3.5.0.76 (the latest commercial version )

## Steps to Reproduce

1. 
2.
3.

## Current Behavior

1、The left and right handles are reversed, 
2、and some keys, such as the remote lever key and left handle function key, are unavailable.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-02-22 11:00
I've a few questions:

1. Were do you see that controller mismatch? In the Wolvic environment? In any specific app?
2. Is the functionality of the controllers also inverted? I mean, do the functionality of the right controller stay on the right or is it also inverted? I'm trying to figure out what do you see is a mere visual issue or something related to the tracking.

**Comment by dingsing2021** [comment] 2022-02-22 11:23
> I've a few questions:
> 
> 1. Were do you see that controller mismatch? In the Wolvic environment? In any specific app?
in Wolvic launcher

> 2. Is the functionality of the controllers also inverted? I mean, do the functionality of the right controller stay on the right or is it also inverted? I'm trying to figure out what do you see is a mere visual issue or something related to the tracking.

the functionality of controllers  not inverted.
the right &left  controller tracking is running normally,It's just that the handle shows the opposite model.
The most important problem is that some key keys fail. Only the home button on the right handle and the trigger button are found to be normal so far.

**Comment by fwei-io** [comment] 2022-02-24 05:02
@dingsing2021 
After installing that SDK version 3.5.0.76 we can reproduce the controller issues. Can you share the latest stable SDK that should be used for that SDK VR Runtime? The one we have still doesn't detect '/interaction_profiles/huawei/6DOFController' and using the previous profile only detects the grip button now. On the Huawei portal we can only find [hvrsdk-openxr-3.0.0.33](https://developer.huawei.com/consumer/cn/doc/development/graphics-Library/openxr-sdk-download-0000001148849243). Which is dated to 2020.

**Comment by fwei-io** [comment] 2022-02-25 21:33
@MortimerGoro @svillar 
HVR team: for [reversed L/R controller and buttons unavailable issue](https://github.com/Igalia/wolvic/issues/47) in Wolvic, please follow the same OpenXR controller profile. It is exactly the same for Quest Touch, but please reverse the L/R controller (patched) settings in Wolvic since VR SDK 3.5.0.76 has corrected this issue. The profile & so file in [hvrsdk-openxr-3.0.0.33](https://developer.huawei.com/consumer/cn/doc/development/graphics-Library/openxr-sdk-download-0000001148849243) remain unchanged and usable.

**Comment by svillar** [comment] 2022-03-03 16:41
> @MortimerGoro @svillar
> HVR team: for [reversed L/R controller and buttons unavailable issue](https://github.com/Igalia/wolvic/issues/47) in Wolvic, please follow the same OpenXR controller profile. It is exactly the same for Quest Touch, but please reverse the L/R controller (patched) settings in Wolvic since VR SDK 3.5.0.76 has corrected this issue. The profile & so file in [hvrsdk-openxr-3.0.0.33](https://developer.huawei.com/consumer/cn/doc/development/graphics-Library/openxr-sdk-download-0000001148849243) remain unchanged and usable.

Sure, we'll remove the previous workaround.

**Comment by fwei-io** [comment] 2022-03-04 00:29
@dingsing2021  update - MortimerGoro had tested reverted the L/R controllers, using the same profile in [hvrsdk-openxr-3.0.0.33](https://developer.huawei.com/consumer/cn/doc/development/graphics-Library/openxr-sdk-download-0000001148849243), however, the buttons are still not working. Please help look into it or provide suggestions, thanks.

**Comment by dingsing2021** [comment] 2022-03-04 02:06
> @dingsing2021 update - MortimerGoro had tested reverted the L/R controllers, using the same profile in [hvrsdk-openxr-3.0.0.33](https://developer.huawei.com/consumer/cn/doc/development/graphics-Library/openxr-sdk-download-0000001148849243), however, the buttons are still not working. Please help look into it or provide suggestions, thanks.

@MortimerGoro @svillar  
here is the newest profile for SDK runtime 3.5.0.76 ; FOR the SDK Runtime  3.5.0.76 , you can get it by HOTA, just make sure the phone connect the internet. MORE details can be found from the closed issues.

XR_HUAWEI_6dof_controller_interaction
Path: /interaction_profiles/huawei/6dof_controller
Valid for user paths:
•	/user/hand/left
•	/user/hand/right
Supported component paths:
•	On /user/hand/left only:
o	…/input/x/click
o	…/input/x/touch
o	…/input/y/click
o	…/input/y/touch
o	…/input/menu/click
•	On /user/hand/right only:
o	…/input/a/click
o	…/input/a/touch
o	…/input/b/click
o	…/input/b/touch
o	…/input/home/click
•	…/input/trigger/value
•	…/input/trigger/click
•	…/input/trigger/touch
•	…/input/thumbstick/x
•	…/input/thumbstick/y
•	…/input/thumbstick/click
•	…/input/thumbstick/touch
•	…/input/grip/value
•	…/input/grip/click
•	…/input/ grip /touch
•	…/input/grip/pose 
•	…/input/aim/pose  
•	…/output/haptic   
XR_HUAWEI_controller_interaction
Path: /interaction_profiles/huawei/controller
Valid for user paths:
•	/user/hand/left
•	/user/hand/right
Supported component paths:
•	…/input/home/click
•	…/input/back/click
•	…/input/volume_up/click
•	…/input/volume_down/click
•	…/input/trigger/value
•	…/input/trigger/click
•	…/input/trackpad/x
•	…/input/trackpad/y
•	…/input/trackpad/click
•	…/input/trackpad/touch
•	…/input/aim/pose
•	…/input/grip/pose
•	…/output/haptic

**Comment by svillar** [comment] 2022-03-22 09:51
There are indeed issues in the aforementioned SDK implementation. We're waiting for a fix.

**Comment by svillar** [comment] 2022-04-01 10:22
I'll leave this open just for tracking purpouses. The issue can be better tracked in the [SDK issue](https://github.com/hms-ecosystem/OpenXR-SDK/issues/26)

**Comment by svillar** [comment] 2022-05-09 10:36
This was fixed in the new SDK and the workaround was removed from wolvic.

**Closed by svillar** 2022-05-09 10:36 UTC
Labels: bug, third party
