### ISSUE TITLE
App data is not removed properly 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1523] opened 2024-08-24 15:15 UTC
## Configuration

Wolvic version: 1.7
Wolvic build ID: 182360411

Hardware: Quest3

## Steps to Reproduce

1. Upgrade Wolvic from a previous version, where there is already some user data in the storage
2. Clear user data from the Wolvic library dialog (eg, history, bookmarks) 
3. Exit the application
4. Launch the System settings dialog and go to the Storage section
5. Remove the Wolvic app data
6. Uninstall Wolvic
7. Install Wolvic
8. Go to the library dialog 

## Current Behavior

There is user data

## Expected Behavior

All the user data should have been removed

## Context

In order to reproduce the issue is key that there is already user data from previous versions of Wolvic.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2024-08-30 08:23
I've tried these steps and cannot reproduce it. Could it be the case that the user has setup a Mozilla account which is synchronizing the data?

**Comment by javifernandez** [comment] 2024-09-02 20:50
> I've tried these steps and cannot reproduce it. Could it be the case that the user has setup a Mozilla account which is synchronizing the data?

That could be the case, indeed. However, I managed to reproduce a "similar" issue without any interaction with a Mozilla account.

**Comment by svillar** [comment] 2024-11-15 11:59
@javifernandez do you have the Meta cloud backup active? Because that might be interferring

**Comment by javifernandez** [comment] 2024-11-16 21:00
> @javifernandez do you have the Meta cloud backup active? Because that might be interferring

It's active indeed, good point. 

I'm going to try to reproduce it without it; perhaps that's root cause if the described behavior.

**Comment by felipeerias** [comment] 2024-11-19 02:02
In this case, my suspicion is that the data being restored comes from a cloud backup. One way to test this is to add one last entry to history and bookmarks before deleting them.

Repeat the steps to reproduce the bug and check if that last entry is there.

Unfortunately, it seems that there isn't a predictable way for us to update cloud backups:

> Backups happen automatically at the following times:
> 
>    - Once per night, when the device is idle, charging, and connected to WiFi, similar to when the system will update the OS.
>    - When the app is uninstalled, if it was installed from the store
>    - Each time the app is exited, up to once every six hours
> 
> Each user can have multiple backup ‘slots’ per purchased app, per headset, and each backup run will not overwrite the previous slot. In addition to automated backups, users can manually request backups by going to the Cloud Backup tab located in device settings.

https://developers.meta.com/horizon/documentation/native/ps-cloud-backup

**Comment by svillar** [comment] 2024-12-11 18:03
Let's close this as it's likely caused by the cloud backup. Please reopen if needed.

A good test would be to try the same steps in another device like Pico. If you cannot reproduce it then it's caused by the cloud backup

**Closed by svillar** 2024-12-11 18:03 UTC
Labels: bug, needinfo, feedback-form
