### ISSUE TITLE
visit https://sketchfab.com/3d-models , 3d-models rending wrong, no texture mapping

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#230] opened 2022-08-09 09:15 UTC
## Configuration

Wolvic version: 1.0.1
Wolvic build ID: 

Hardware: huawei vr glass 3dof

## Steps to Reproduce

1.  visit https://sketchfab.com/3d-models 
2.  enter the vr mode,  3d-models rending wrong

## Current Behavior

enter the vr mode,loading 3d models,   3d-models rending wrong,no texture mapping

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-08-09 18:18
Please provide specific examples of models not working, because I've tried 3 different ones with the 6DoF version and all of them worked fine.

**Comment by dingsing2021** [comment] 2022-08-10 01:06
I have tried these 3D models, 
https://sketchfab.com/3d-models/yor-eb40444c37a24229a8d0e9499945f168
https://sketchfab.com/3d-models/jiotto-caspita-f1-road-car-1989-by-alexka-828c84b390624f0389287bd036d7dbf5

here is some details
1, when visit this page, which is a preview of all 3D models,  it seems OK, 
https://sketchfab.com/3d-models?date=week&sort_by=-likeCount&cursor=cD0yNg%3D%3D
2, when click a 3d models,  Loading 3D models, it seems wrong,  no texture mapping.
https://sketchfab.com/3d-models/yor-eb40444c37a24229a8d0e9499945f168

**Comment by dingsing2021** [comment] 2022-08-10 01:13
![IMG_20220810_090222](https://user-images.githubusercontent.com/86649949/183788753-04b48fad-9f91-4fa7-ba77-ae01a226012e.jpg)
![IMG_20220810_085916](https://user-images.githubusercontent.com/86649949/183788772-4035e108-6a4f-4f65-88ce-8bb03b422270.jpg)
![IMG_20220810_085701](https://user-images.githubusercontent.com/86649949/183788801-a21c1ca9-dd92-4c03-b149-dd45bfca2ad4.jpg)

**Comment by dingsing2021** [comment] 2022-08-10 01:29
![ScreenShotVR_20220810092007](https://user-images.githubusercontent.com/86649949/183790467-86053d9d-7cbe-4450-805b-8
![ScreenShotVR_20220810092000](https://user-images.githubusercontent.com/86649949/183790504-379a3b88-8828-4ab5-906c-724dab497c26.jpg)
bc1268f1555.jpg)
![ScreenShotVR_20220810091952](https://user-images.githubusercontent.com/86649949/183790536-489f984f-4448-4fee-889d-1ba51caac713.jpg)
![ScreenShotVR_20220809171104](https://user-images.githubusercontent.com/86649949/183790542-599f6089-c685-4b9a-8576-d1f891922135.jpg)
![ScreenShotVR_20220809171054](https://user-images.githubusercontent.com/86649949/183790544-d9222e0c-7e8b-4dbb-bc21-5f1ef06d4458.jpg)

**Comment by svillar** [comment] 2022-09-01 15:42
I've just tried with these two and they worked fine for me. Does it happen all the time to you? Because I've seen this issue sometimes in desktop browsers. I don't think there is any issue with Wolvic, unless you see this issue always

**Comment by svillar** [comment] 2022-10-11 16:50
No reply from reported in 2 months. We are unable to reproduce it using the latest version either. Closing this then.

Please do reopen if you can reproduce it again. Thanks!

**Closed by svillar** 2022-10-11 16:50 UTC
Labels: question
