### ISSUE TITLE
Tabs get closed with updates

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#939] opened 2023-08-29 06:19 UTC
## Configuration

Wolvic version: 1.4.2
Wolvic build ID: 

Hardware:  Oculus Quest2 

## Steps to Reproduce

1. Open several tabs 
2. Upgrade Wolvic
3.

## Current Behavior

All the tabs held by the previous version of Wolvic are lost after upgrading

## Expected Behavior

Wolvic should preserve tabs after upgrading

**Comment by HollowMan6** [comment] 2023-09-02 12:46
I don't think there's any good way to fix this. WindowState is saved at `/data/user/0/com.igalia.wolvic/files/windows_state.json`, and can be cleared out during the upgrade.

**Comment by svillar** [comment] 2023-09-04 09:19
I guess the only thing we can do is to check why it's deleted, because AFAIK upgrading does not clear some other settings, so the session should be there too. Perhaps we have some code to discard it in case of upgrades but I really doubt it...

Also I don't think the system deletes those kinds of user data even when upgrading. Anyway we should basically discard that we don't clear it. If we are not the ones deleting the session state then this should be a wontfix.

**Comment by bkardell** [comment] 2023-10-02 21:43
> I don't think there's any good way to fix this. 

Idk, I have just dozens of open sites in each of many browsers and when I upgrade, on any OS, they don't get closed (except in FF on mac sometimes). I can see how this would be frustrating.  Are there before and after events or something for installs?

**Comment by javifernandez** [comment] 2024-03-12 21:50
We have got another report via the feedback form:

> With every update all opened tabs are gone. Please fix that. When i mark all tabs it would be good to add them to bookmarks all at once.

**Comment by svillar** [comment] 2024-08-23 23:21
I cannot reproduce it with latest 1.7 update. Please reopen if you can still reproduce it

**Closed by svillar** 2024-08-23 23:21 UTC
Labels: priority-low, unconfirmed, feedback-form
