### ISSUE TITLE
Freeze when activating and desactivating the screen's curve mode 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#590] opened 2023-03-30 12:58 UTC
## Configuration

Wolvic version: 1.3.3
Wolvic build ID:  versionCode 83

Hardware: Ocullus Quest2 (SW: 49.0.0.207)

## Steps to Reproduce

1. Go to Settings -> Visualization 
2. Toggle the "Enable curve screen button" (initially disabled)
3. Repeat step 2 

## Current Behavior

The app gets freeze.

## Expected Behavior

The app continue running, the toggle button updated and the screen switches between curve and flat modes. 

## Possible Solution

Not a solution, but it seems the App go back to normal running after letting the device going to sleep mode (the settings menu window is hidden)

## Error Logs and Stack Traces

<details open>
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  java.lang.IllegalStateException: Surface has already been released.
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.checkNotReleasedLocked(Surface.java:664)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.lockHardwareCanvas(Surface.java:437)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UISurfaceTextureRenderer.drawBegin(UISurfaceTextureRenderer.java:5)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:10)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:3)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20852)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3820)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3526)
2023-03-30 14:53:58.883  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2797)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1755)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7821)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doFrame(Choreographer.java:726)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.handleCallback(Handler.java:886)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.dispatchMessage(Handler.java:102)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Looper.loop(Looper.java:227)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.app.ActivityThread.main(ActivityThread.java:7436)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at java.lang.reflect.Method.invoke(Native Method)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2023-03-30 14:53:58.884  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  java.lang.IllegalStateException: Surface has already been released.
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.checkNotReleasedLocked(Surface.java:664)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.lockHardwareCanvas(Surface.java:437)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UISurfaceTextureRenderer.drawBegin(UISurfaceTextureRenderer.java:5)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:10)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:3)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20852)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3820)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3526)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2797)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1755)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7821)
2023-03-30 14:53:58.894  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doFrame(Choreographer.java:726)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.handleCallback(Handler.java:886)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.dispatchMessage(Handler.java:102)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Looper.loop(Looper.java:227)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.app.ActivityThread.main(ActivityThread.java:7436)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at java.lang.reflect.Method.invoke(Native Method)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2023-03-30 14:53:58.895  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-03-30 14:53:59.011  7682-9825  VrApi                   com.igalia.wolvic.metastore          I  FPS=90/90,Prd=24ms,Tear=0,Early=0,Stale=0,Stale2/5/10/max=0/0/0/0,VSnc=0,Lat=-1,Fov=0,CPU4/GPU=2/1,1171/400MHz,OC=FF,TA=0/0/0,SP=N/N/N,Mem=1353MHz,Free=3157MB,PLS=0,Temp=30.5C/0.0C,TW=4.20ms,App=1.69ms,GD=0.00ms,CPU&GPU=5.40ms,LCnt=8(DR0,LM0),GPU%=0.55,CPU%=0.09(W0.10),DSF=1.00,CFL=14.47/19.75,LD=0
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  java.lang.IllegalStateException: Surface has already been released.
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.checkNotReleasedLocked(Surface.java:664)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.lockHardwareCanvas(Surface.java:437)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UISurfaceTextureRenderer.drawBegin(UISurfaceTextureRenderer.java:5)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:10)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:3)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20852)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.draw(View.java:21707)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20843)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.draw(View.java:21707)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20843)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.draw(View.java:21707)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20843)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.draw(View.java:21707)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.draw(View.java:21978)
2023-03-30 14:53:59.734  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.policy.DecorView.draw(DecorView.java:808)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20852)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3820)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3526)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2797)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1755)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7821)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doFrame(Choreographer.java:726)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.handleCallback(Handler.java:886)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.dispatchMessage(Handler.java:102)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Looper.loop(Looper.java:227)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.app.ActivityThread.main(ActivityThread.java:7436)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at java.lang.reflect.Method.invoke(Native Method)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2023-03-30 14:53:59.735  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-03-30 14:53:59.742  7682-7682  System.err              com.igalia.wolvic.metastore          W  java.lang.IllegalStateException: Surface has already been released.
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.checkNotReleasedLocked(Surface.java:664)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Surface.lockHardwareCanvas(Surface.java:437)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UISurfaceTextureRenderer.drawBegin(UISurfaceTextureRenderer.java:5)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:10)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.igalia.wolvic.ui.widgets.UIWidget.draw(UIWidget.java:3)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20852)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.View.updateDisplayListIfDirty(View.java:20812)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3820)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3526)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2797)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1755)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7821)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer.doFrame(Choreographer.java:726)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.handleCallback(Handler.java:886)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Handler.dispatchMessage(Handler.java:102)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.os.Looper.loop(Looper.java:227)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at android.app.ActivityThread.main(ActivityThread.java:7436)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at java.lang.reflect.Method.invoke(Native Method)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2023-03-30 14:53:59.743  7682-7682  System.err              com.igalia.wolvic.metastore          W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
```

</details>

**Comment by svillar** [comment] 2023-03-30 17:49
That was caused by I mistake I committed generating the packages, I reintroduced #554 by mistake :disappointed:

**Closed by svillar** 2023-03-30 17:49 UTC
