### ISSUE TITLE
Not working <input type="file">

### ISSUE THREAD

**Issue by JackDesBwa** [Igalia/wolvic#308] opened 2022-10-23 11:17 UTC
## Configuration

Wolvic version: 1.1.1
Wolvic build ID: 76be4c84 (AC 63.0.0) versionCode 50
Hardware: Quest2

Also just observed in an old version of Firefox Reality, but working with meta browser. (both on the same hardware)

Wolvic has file access permission of Android enabled.

## Steps to Reproduce

1. Visit a page with a `<input type="file">` field. For example https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
2. Click on the field ("Browse..." button)

## Current Behavior

Nothing visible happens

## Expected Behavior

A file dialog should open to choose a local file.

Optionally, an alert box could open if file access permission is disabled: average user might not think about it.

## Context

The page https://stereopix.net/viewer allows to use the viewer of this site to show stereoscopic images and videos without uploading them to the sharing website. When choosing "File on the computer [not uploaded]", a `<input type="file">` field is shown and we can select the file to process.

With Wolvic, it is not possible to select the file. I observed that the behavior is not related to this site, and wrote a more general issue.

I attach an image in a format compatible with other fields let to default in the form, although any image will show the defective behavior. With this one, you would be able to use this page and display a content in the WebXR session without painful content for the eyes.
![test_image](https://user-images.githubusercontent.com/493717/197388565-c2c3a0a1-6051-4c8f-a8bc-5953d1635a53.png)

**Comment by svillar** [comment] 2022-10-23 15:43
So the problem here is is not that the input type is not supported, it's that we haven't resolved the issue of showing a system dialog without exiting the Wolvic VR environment. Although this report is amazing and well documented I think we can handle it in #208. Thanks!

Duplicate of #208

**Closed by svillar** 2022-10-23 15:43 UTC

**Comment by JackDesBwa** [comment] 2022-10-23 15:49
Oh, I searched for already reported issue, but haven't found this one, sorry.

**Comment by svillar** [comment] 2022-10-23 15:52
> Oh, I searched for already reported issue, but haven't found this one, sorry.

No worries, it was not obvious at all from the title. Thanks for reporting!
