### ISSUE TITLE
No video playback unless I mute the video

### ISSUE THREAD

**Issue by SEBADA321** [Igalia/wolvic#1610] opened 2024-10-30 01:07 UTC
## Configuration

Wolvic version: 1.7.1
Wolvic build ID: 183022222

Hardware:  Meta Quest 3

## Steps to Reproduce
1. Navigate to Youtube or other video streaming website.
2. Play any video ( at any resolution )
3.  Mute video to have normal playback

## Current Behavior
No video playback unless I mute the video

## Expected Behavior
Normal playback with sound

```
```

</details>

**Comment by asianfiji** [comment] 2024-10-30 02:08
Same issue here with Q3. Video freezes if theres audio and on mute, starts to play again. Happening after the update

**Comment by SEBADA321** [comment] 2024-10-30 06:26
Managed to fix it (don't know if it is permanent). I disabled UI hardware acceleration inside the Wolvic settings. Then it forces you to reboot (the app) and everything seems to be back to normal. 
Just to test further, I then reset the developer settings (so that it enables back the hardware acceleration), reboot the app again and the problem was still solved.

**Comment by javifernandez** [comment] 2024-10-30 09:18
I can confirm the bug in the following configurations:
  -  Wolvic 1.7.1 /  Quest3 / SO version 69.0.0.570

Non reproducible in the following configurations:
  -  Wolvic 1.7.1 / Quest2 / SO version 71.0.0.278
  - Chromium 1.1 / Quest2 / SO version 69.0.0.570
  - Chromium 1.1 / Quest3 / SO version 69.0.0.570
  - Wolvic 1.7.0 / Quest3 / SO version 69.0.0.570

So this is clearly a regression from 1.7.0, that affects only the Quest3 / SO version 69.0.0.570 configuration.

**Comment by MarkVonBlugen** [comment] 2024-10-30 15:39
Same issue on Quest 3, please fix it fast, and maybe add zoom in and out feature, while you're at it

**Comment by svillar** [comment] 2024-10-30 19:01
So we've just released a new package in the store "fixing" this issue. After bisecting we've concluded that the first commit showing this issue is the one adding the version check activity. That is not really needed for Meta because the store has its own checks so we can safely remove it.

However we don't understand why this is happening, and why so many different things can trigger the issue. That's why we'll leave the issue open for further research.

**Comment by FrozenAlex** [comment] 2024-11-22 09:40
I have the same issue on quest 3 v72 ptc

**Comment by svillar** [comment] 2024-11-22 10:00
> I have the same issue on quest 3 v72 ptc, the video just lags and stays on the same place

That's correct, I've just seen it as well. This is going to be a headache. Thanks for reporting!

**Comment by svillar** [comment] 2024-11-22 12:10
I'm sessing codec issues in the logs:
```
13:09:14.719 20212-20301 System.err            W  android.media.MediaCodec$CodecException: Error 0xffffff92
13:09:14.719 20212-20301                       W  	at android.media.MediaCodec.native_flush(Native Method)
13:09:14.719 20212-20301                       W  	at android.media.MediaCodec.flush(MediaCodec.java:2350)
13:09:14.719 20212-20301                       W  	at org.mozilla.gecko.media.LollipopAsyncCodec.flush(LollipopAsyncCodec.java:196)
13:09:14.719 20212-20301                       W  	at org.mozilla.gecko.media.Codec.flush(Codec.java:623)
13:09:14.719 20212-20301                       W  	at org.mozilla.gecko.media.ICodec$Stub.onTransact(ICodec.java:169)
```

**Comment by svillar** [comment] 2024-11-22 12:23
And this
```
13:22:36.871  2329-2502  GeckoRemoteCodec      E  codec creation error
                                                  android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                  	at android.media.MediaCodec.native_configure(Native Method)
                                                  	at android.media.MediaCodec.configure(MediaCodec.java:2176)
                                                  	at android.media.MediaCodec.configure(MediaCodec.java:2092)
                                                  	at org.mozilla.gecko.media.LollipopAsyncCodec.configure(LollipopAsyncCodec.java:164)
                                                  	at org.mozilla.gecko.media.Codec.configureCodec(Codec.java:535)
                                                  	at org.mozilla.gecko.media.Codec.configure(Codec.java:423)
                                                  	at org.mozilla.gecko.media.ICodec$Stub.onTransact(ICodec.java:128)
                                                  	at android.os.Binder.execTransactInternal(Binder.java:1179)
                                                  	at android.os.Binder.execTransact(Binder.java:1143)
13:22:36.955  2329-2700  MediaCodec            I  MediaCodec will operate in async mode
```

**Comment by svillar** [comment] 2024-11-22 12:32
@FrozenAlex have you tried with the Meta browser? I ask because while playing some side by side 3D videos the playback gets constantly stuck. Not permanently but for 3-4 seconds. I suspect there is some issue with media codecs in the PTC release.

**Comment by FrozenAlex** [comment] 2024-11-22 13:10
@svillar Yeah it seems like they completely broke codecs in this release. Just checked in the built in browser and it dies too, in the same way. OS version 72.0.0.368.347.665705819

**Comment by FrozenAlex** [comment] 2024-11-22 19:28
@svillar Sure, I like to beta test stuff and send issue reports. I'll drop you an email a bit later.

**Comment by FrozenAlex** [comment] 2024-11-22 22:09
@davehill00 probably on any yt video. I was watching insym latest video afaik https://www.youtube.com/watch?v=km2iPEKr6Y0 I do have yt premium if it makes any difference

**Comment by mounirlamouri** [comment] 2024-11-22 22:14
> @svillar Yeah it seems like they completely broke codecs in this release. Just checked in the built in browser and it dies too, in the same way. OS version 72.0.0.368.347.665705819, even on youtube...

Do you have some logs showing the error? Something similar to what @svillar put in the [comment above](https://github.com/Igalia/wolvic/issues/1610#issuecomment-2493636880).

**Comment by FrozenAlex** [comment] 2024-11-22 22:26
@davehill00 weird, I put on my headset again and the issue went away.. I rebooted and the issue came back when I turned on my bluetooth headset

**Comment by FrozenAlex** [comment] 2024-11-22 22:30
@davehill00 the logs, I went into wolvic and then into the meta quest browser, connected my bluetooth headset and the videos froze
[logcat.zip](https://github.com/user-attachments/files/17876987/logcat.zip)

**Comment by FrozenAlex** [comment] 2024-11-22 22:32
Lmfao. I need to private this comment

**Comment by FrozenAlex** [comment] 2024-11-22 22:44
I'm gonna get a cleaner log and post it here in a bit

**Comment by FrozenAlex** [comment] 2024-11-22 22:50
@davehill00 this is when playing that Insym video and fast forwarding. Bluetooth headphones connected. Audio plays, video stays frozen
[logcat.log](https://github.com/user-attachments/files/17877210/logcat.log)

**Comment by mounirlamouri** [comment] 2024-11-22 23:11
@FrozenAlex can you repro the issue without using your Bluetooth headphones?

@svillar are you also using Bluetooth headphones by any chance?

**Comment by FrozenAlex** [comment] 2024-11-22 23:13
@mounirlamouri Video goes back to normal immediately when I disconnect

**Comment by mounirlamouri** [comment] 2024-11-22 23:37
Thanks for the info, I was able to reproduce the issue. We will work on a fix.

**Comment by svillar** [comment] 2024-11-23 18:30
> @FrozenAlex can you repro the issue without using your Bluetooth headphones?
> 
> @svillar are you also using Bluetooth headphones by any chance?

Not at all. That said the issue is not 100% reproducible. Sometimes it fails in some executions in a row, but yesterday I was debugging some other issues and didn't get it in the whole afternoon/evening. In any case not using any BT device or the like (although BT was on)

**Comment by javifernandez** [comment] 2024-12-03 22:16
Bug not reproduce in the following configurations:

- Wolvic 1.7.1 / Quest2 / SO version 72.0.0.505.347
- Wolvic 1.7.1 / Quest3 / SO Version 71.0.0.505.522

**Closed** 2024-12-04 10:08 UTC
Labels: bug, release-blocker

**Comment by Qamar4P** [comment] 2024-12-12 07:26
@javifernandez @svillar Working fine in Quest 3 and PicoXR Neon Pro, in my case, this could be an issue with the vendor implementation. Could you briefly highlight, what needs to be fixed on vendor side to comply OpenXR standards?
