### ISSUE TITLE
Wolvic Browser Fails to Launch

### ISSUE THREAD

**Issue by tpaclatee** [Igalia/wolvic#202] opened 2022-07-16 22:52 UTC
## Hardware

Wolvic Version: 
latest prod build as of 7/16/22 (1.0)

Quest 2 Version: 
System Version 35444700575000000
Version 42.0.0.130.250.381640954
Runtime Version 42.0.0.130.250.381640810
OS Version user-35444700575000000

## Steps to Reproduce

1. Launch app from library
2. Open app in any fashion
3. Persists after reinstalling and restart

## Current Behavior

The app will fail to launch. A Quest loading screen appears briefly and then the user is returned to the home area with a message that "Wolvic keeps stopping" and fails to launch or "is taking too long to respond". No app splash screen appears.

## Expected Behavior

The app should launch when selected from the user's library. The app should show a loading screen and then display the Wolvic splash screen while the app loads. It should be safely exitable and able to start when selected. 

## Possible Solution

Determine the cause of the crash. Test for issues when the app is being loaded. Determine memory usage and find what is causing the hangs.

## Context

The app was updated/reinstalled and no longer able to be launched. This occurred only recently, after an update to the app. Cannot enter the app at all under any circumstances and there does not seem to be a workaround. 

## Error Logs and Stack Traces

<details open>
logcat returned nothing when app crashes

```
```

</details>

**Comment by elima** [comment] 2022-07-18 09:08
This has been confirmed and we are working on a fix. 

The issue is caused by incompatibility between saved logins database between Wolvic 1.0 and older versions.

A temporary fix is to remove Wolvic's app data in Settings -> Storage.

Thanks for reporting it!

**Comment by svillar** [comment] 2022-07-25 11:18
This will be fixed by pull #204

**Comment by svillar** [comment] 2022-07-28 09:53
Included a fix in 1.0.1. Please reopen if you hit it again.

**Closed by svillar** 2022-07-28 09:53 UTC
Labels: bug, question
