### ISSUE TITLE
Crash on Quest 2 with UPDATE v51

### ISSUE THREAD

**Issue by Joinn99** [Igalia/wolvic#613] opened 2023-04-15 08:25 UTC
## Configuration

Wolvic version: 1.3.3 CodeVersion 84
Wolvic build ID: Sorry cannot open it to check it.

Hardware: Quest 2 128GB
Version: 51.0.0.173.268.463372067

## Steps to Reproduce

Open, and it crashes.

## Possible Solution

This issue has been reported by serveal users in  #606. I didn't experience this issue until I rebooted my Quest 2 and it did an **automatic system update** to v51, then I couldn't open Wolvic anymore.

Seems not only this version, but all previous versions of Wolvic have the same issue. I have tested 1.3.3, 1.3.2, 1.0.2, and they all crashed.

```
```

</details>

**Comment by mikemucc** [comment] 2023-04-15 15:22
I wondered if it might be a Firmware update that caused it... this seems more plausible than an update to Wolvic.

**Comment by javifernandez** [comment] 2023-04-17 21:53
I'm not able to reproduce the crash in my system:

Hardware: Quest 2 128GB
Version: 50.0.0.195.257.454885341

**Comment by mikemucc** [comment] 2023-04-17 22:22
Yeah, you're definitely behind by a version...

Hardware: Quest 2 128GB

From the Software Updates Dialog:

OS Version:
SQ3A.220605.009.A1

Version:
51.0.0.173.268.463372067

Runtime Version 
51.0.0.173.269.463372413

System Version:
50327160085300150

**Comment by javifernandez** [comment] 2023-04-17 22:36
Closing this as dup of #606

**Closed by javifernandez** 2023-04-17 22:36 UTC
