### ISSUE TITLE
Bad distortion in several projects

### ISSUE THREAD

**Issue by Sgeo** [Igalia/wolvic#43] opened 2022-02-19 04:23 UTC
## Configuration

Wolvic version: 0.9.4
Wolvic build ID: 741e5072 (AC 63.0.0)

Hardware: Oculus Quest 2

## Steps to Reproduce

1. Visit and enter VR in any of the following sites:
2. https://spiderman.webvr.link/
3. https://aframe.io/examples/showcase/helloworld/
4. https://mixedreality.mozilla.org/hello-webxr/

## Current Behavior
There is a bad distortion, especially notable when rolling head left and right (instead of turning left/right or looking up/down)

## Expected Behavior
There should be a comfortable VR experience

## Possible Solution
I wonder if Wolvic is providing the proper projection matrices.

Or these projects could have a bug. Spiderman seems to be based on A-Frame, although Hello WebXR looks unrelated to A-Frame (I may be mistaken)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by msub2** [comment] 2022-02-19 05:02
What is your IPD slider set to? For some reason only the middle setting seems to display WebXR experiences without distortion. I was also trying to figure this out in Firefox Reality but I can't seem to find any way of detecting where the slider is set to so I can compensate for it.

**Comment by Sgeo** [comment] 2022-02-19 05:29
My IPD slider is set to the smallest setting, and yeah, middle setting seems fine.

That's a little bit confusing, shouldn't WebXR receive projection and view matrices? Trying to fix the problem by detecting IPD seems like a hack. Although if I wanted to know IPD I'd wonder if I could look at the two view/eye matrices, inverse one and multiply by the other, and examine that.

**Comment by MortimerGoro** [comment] 2022-02-21 19:15
We made some changes recently in Gecko matrix multiplication, maybe this caused a regression, we'll check that.

Also related, I had a WIP patch to improve eye offset math in Gecko, as internally only used position based offset and it's better to include a transform, some devices might set additional values other than translation

**Comment by RickAndTired** [comment] 2022-04-13 06:34
Wolvic version 0.9.5
f9678560 (AC 63.0.0)
Oculus Quest 2 (tested on 4 different headsets)

I am also getting the same bug

This only happens on IPD setting 1 and 3
The bug is not present on IPD 2

This bug has also been present in Firefox Reality since Oct 2020

**Comment by elima** [comment] 2022-04-28 12:28
This doesn't happen in Huawei VR, so looks like an issue in oculusvr backend.

**Comment by svillar** [comment] 2022-06-07 07:14
This was fixed by @felipeerias in pull #134

**Closed by svillar** 2022-06-07 07:14 UTC
Labels: bug, priority-high
