### ISSUE TITLE
View centering in Meta Quest 2 only affects X axis

### ISSUE THREAD

**Issue by GuerreroNinja** [Igalia/wolvic#484] opened 2023-02-12 11:01 UTC
## Configuration

Wolvic version: 1.3
Wolvic build ID: 

Hardware: Meta Quest 2

## Steps to Reproduce

1. Open Wolvic browser in a Meta Quest 2 headset.
2. Look up and long press right controller Oculus button to center the view.
3. The browser screen does not move in front of you, only on X axis.

## Current Behavior

This don't happen on Wolvic 1.2 or Firefox last version, both work as intended. You can't use the browser looking up or down, only front.

## Expected Behavior

It should work as in 1.2 or Firefox.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by odgittyup** [comment] 2023-02-13 03:21
I can confirm this, you cannot change the Y-Axis and this is annoying. My neck hurts. When I'm in the recliner, I can't use this headset. When I lift weights (on back, or at an angle, I can't watch he workout vids unless straight forward. Please change it so that RE-CENTER can work vertically.

**Comment by koopicoolest** [comment] 2023-02-14 11:56
was working like 2 weeks ago, def a problem with 1.3.

**Comment by GuerreroNinja** [comment] 2023-02-14 12:00
> was working like 2 weeks ago, def a problem with 1.3.

Yes, the bug was introduced in 1.3 update and we can't rollback on Quest (or I don't know how to, as I can't activate the Quest developer mode and sideloading the previous version).

**Comment by svillar** [comment] 2023-02-14 13:25
> > was working like 2 weeks ago, def a problem with 1.3.
> 
> Yes, the bug was introduced in 1.3 update and I can't rollback on Quest (or I don't know how to, as I can't activate the Quest developer mode and sideloading the previous version). So I went back to the "old and trusty" Firefox (which implies serious security concerns as it is really old by now) as for me Wolvic is now unusable.

So we know where the problem is, it's indeed a regression of switching to OpenXR APIs. The recentering code was using an OculusVR API that is able to detect them. We just need a way to detect that using OpenXR APIs, because the recentering code it's already there and works fine.

**Comment by GuerreroNinja** [comment] 2023-02-14 13:29
>
> So we know where the problem is, it's indeed a regression of switching to OpenXR APIs. The recentering code was using an OculusVR API that is able to detect them. We just need a way to detect that using OpenXR APIs, because the recentering code it's already there and works fine.

So the recentering code changes in OpenXR API and should be adjusted... I suppose there are other open source developments that use OpenXR and do the recentering thing in both axis, so checking them would be interesting. A pity I can't have a developer account to sideload things in my Meta Quest, I wish I could lend a hand here.

**Comment by svillar** [comment] 2023-02-15 11:49
We have a fix for this that we plan to release soon, but note that you can already recenter the view. Just
1. single click on Oculus button
2. go to "Quick Settings"
3. recenter view

**Comment by GuerreroNinja** [comment] 2023-02-16 11:25
> We have a fix for this that we plan to release soon, but note that you can already recenter the view. Just
> 
>     1. single click on Oculus button
> 
>     2. go to "Quick Settings"
> 
>     3. recenter view

I follow this steps but Wolvic screen does not get recentered in Y axis in my Meta Quest 2, just it is the same as a long press the Oculus button. I will wait for the patch to get into main and the update is implemented. Thank you!

**Comment by svillar** [comment] 2023-02-16 11:36
> > We have a fix for this that we plan to release soon, but note that you can already recenter the view. Just
> > ```
> > 1. single click on Oculus button
> > 
> > 2. go to "Quick Settings"
> > 
> > 3. recenter view
> > ```
> 
> I follow these steps but Wolvic screen does not get recentered in Y axis in my Meta Quest 2, it is just the same as a long press the Oculus button. I will wait for the patch to get into main and the update is implemented. Thank you!

Weird because I've just tried and it works fine, note that the recentering effectively happens after closing the system menu

**Comment by GuerreroNinja** [comment] 2023-02-16 11:45
> > > We have a fix for this that we plan to release soon, but note that you can already recenter the view. Just
> > > ```
> > > 1. single click on Oculus button
> > > 
> > > 2. go to "Quick Settings"
> > > 
> > > 3. recenter view
> > > ```
> > 
> > 
> > I follow these steps but Wolvic screen does not get recentered in Y axis in my Meta Quest 2, it is just the same as a long press the Oculus button. I will wait for the patch to get into main and the update is implemented. Thank you!
> 
> Weird because I've just tried and it works fine, note that the recentering effectively happens after closing the system menu

You mean the icon with the 4 arrows in quick settings?

[meta-quest-air-link-wireless-pc-vr](https://user-images.githubusercontent.com/32348882/219356354-961a7974-a3ea-4ae2-991b-48740a00d882.jpg)

(Sorry got the image from Google, it shows the previous UI, but the new one is the same icon).

**Closed** 2023-02-17 09:20 UTC
Labels: bug

**Comment by svillar** [comment] 2023-02-17 13:02
To be released in 1.3.1
