### ISSUE TITLE
visit https://www.720yun.com/, some 360 pictures display abnormal

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#224] opened 2022-08-05 07:52 UTC
## Configuration

Wolvic version: 1.0.1
Wolvic build ID: 

Hardware: huawei vr glass 3dof

## Steps to Reproduce

1. enter https://www.720yun.com/,   largest HD/4K/8K/16K 360 image/video portal in china. 
2.  chose some 360 pictures display abnormal，enter the vr mode,for example: https://720yun.com/t/2evkby8h51m?scene_id=90048754
3. some picture display abnormal，Causes dizziness

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-08-09 09:37
Mind attaching a screenshot so we could know what's going on?

**Comment by dingsing2021** [comment] 2022-08-09 10:11
> 

screenshot could not show this issue.it is difficult to describe the problem, I think you should take experience to get that.

**Comment by svillar** [comment] 2022-08-09 18:22
I've tried in Oculus and what I see is that the rotation is inverted, whenever you look up image goes down and viceversa, is that what you have seen?

**Comment by svillar** [comment] 2022-08-09 18:33
This is a duplicate of #221 BTW

**Closed by svillar** 2022-08-09 18:33 UTC
