### ISSUE TITLE
Input randomly locks

### ISSUE THREAD

**Issue by GXboy12345** [Igalia/wolvic#728] opened 2023-06-14 08:07 UTC
## Configuration

Wolvic version: 1.3.4
Wolvic build ID: 88

Hardware: Quest 2 V...0659

## Steps to Reproduce

Browse using Wolvic for a time (usually after inactivity/watching video)

## Current Behavior

refresh, private browsing, new tab or other wolvic elements when pressed have no effect
can't interact with web pages, only scrolling
## Expected Behavior

Regular functionality
## Possible Solution

Putting quest into sleep and re-enterring passwordfixes
## Context

this also happened in firefox reality

```
```

</details>

**Comment by svillar** [comment] 2023-06-14 11:54
Is this with hand tracking enabled (even if not used)? Because we've recently [fixed a bug](https://github.com/Igalia/wolvic/pull/670) related to that.

**Comment by GXboy12345** [comment] 2023-06-17 06:51
System yes, but not used. If Wolvic has a setting, I am not aware of it.

**Comment by svillar** [comment] 2023-06-19 09:13
> System yes, but not used. If Wolvic has a setting, I am not aware of it.

Can you retry with 1.4 ?

**Comment by svillar** [comment] 2023-07-04 15:01
This should be fixed in 1.4. Please do reopen if you can still reproduce it.

**Closed by svillar** 2023-07-04 15:01 UTC
Labels: bug, needinfo
