### ISSUE TITLE
Video plays with audio but image is black

### ISSUE THREAD

**Issue by felislynx-silae** [Igalia/wolvic#223] opened 2022-08-04 04:41 UTC
## Configuration
This happens on wolvic built from main branch, it works on one from shop.

Hardware: Meta Quest 2

## Steps to Reproduce
1. Go to: https://evryplace.com/p/xkupag-ceresit-virtual-house
2. Go to scene with video widget
3. Play

## Current Behavior
Video playback starts, audio is present but for image i get black canvas

## Expected Behavior
It should work like on browser from oculus appstore. For some reason if i build from Main or from Tag it won't work

## Context
I want to build Wolvic with hardcoded webpage. It would be used with managexr to display it in kiosk mode.
I've checked that Wolvic from main reports gecko 96 to my server and one from appstore reports gecko 98. I've tried to change gecko versions and android components etc. but i couldn't manage to find correct ones that would fix the issue

## Error Logs and Stack Traces
<details open>

```
2022-08-03 09:29:14.351 28055-28076/com.igalia.wolvic W/VideoCapabilities: Unsupported mime image/vnd.android.heic
2022-08-03 09:29:14.358 28055-28076/com.igalia.wolvic W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2022-08-03 09:29:14.359 28055-28076/com.igalia.wolvic W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2022-08-03 09:29:14.413 28055-28111/com.igalia.wolvic W/Codec2Client: query -- param skipped: index = 1107298332.
2022-08-03 09:29:14.797 27598-28048/com.igalia.wolvic E/libOpenSLES: Configuration error: unknown key
2022-08-03 09:29:14.797 27598-28048/com.igalia.wolvic W/libOpenSLES: Leaving AndroidConfiguration::GetConfiguration (SL_RESULT_PARAMETER_INVALID)
2022-08-03 09:29:14.807 27598-27749/com.igalia.wolvic W/Web Content: [JavaScript Warning: "WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros." {file: "evr.min.js" line: 6}]
2022-08-03 09:29:14.807 27598-27749/com.igalia.wolvic W/Web Content: [JavaScript Warning: "WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization." {file: "evr.min.js" line: 6}]
2022-08-03 09:29:14.823 27598-27749/com.igalia.wolvic W/Web Content: [JavaScript Warning: "WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros." {file: "evr.min.js" line: 6}]
```

</details>

**Comment by svillar** [comment] 2022-08-04 14:31
For the released packages we are not using Gecko upstream but we have our own fork with some downstream changes. That's perhaps the reason why you're getting issues.

You should build this branch https://github.com/Igalia/gecko-dev/tree/wolvic_release and then include the following in your `local.properties` file:
```
dependencySubstitutions.geckoviewTopsrcdir=PATH_TO_GECKO_DEV
dependencySubstitutions.geckoviewTopobjdir=PATH_TO_GECKO_DEV/obj-aarch64-unknown-linux-android
```

**Comment by felislynx-silae** [comment] 2022-08-05 05:37
@svillar this gecko fork is giving lots of issues on m1 mac, do you have any hints what is required for it to build without issues?

**Comment by svillar** [comment] 2022-08-05 07:49
> @svillar this gecko fork is giving lots of issues on m1 mac, do you have any hints what is required for it to build without issues?

We're using linux to build gecko so I don't have much experience doing it in Mac. All can say is to refer to the [official documentation](https://firefox-source-docs.mozilla.org/setup/macos_build.html)

From my experience, people having troubles building Gecko don't have the right dependencies in their systems to build it. The Gecko build very rarely fails, the problem is normally that the bootstrap process didn't go well.

**Comment by svillar** [comment] 2022-09-06 16:12
I'm closing this since the problem is that Wolvic was not built using the proper version of Gecko.

**Closed by svillar** 2022-09-06 16:12 UTC
