### ISSUE TITLE
fullscreen video doesn't scale to resized window automatically

### ISSUE THREAD

**Issue by azumukupoe** [Igalia/wolvic#143] opened 2022-06-14 05:13 UTC
## Configuration

Wolvic version: 0.9.6
Wolvic build ID: 33

Hardware: Quest 2

## Steps to Reproduce

1. Open webpage with video (for example: https://www.youtube.com/watch?v=aqz-KE-bpKQ)
2. Enter fullscreen
3. The video is cropped

## Context

![image](https://user-images.githubusercontent.com/31339007/173497854-79412ca3-707b-433a-b26c-bbeca98e34a0.png)
![image](https://user-images.githubusercontent.com/31339007/173497866-009e0e40-18f7-47d3-bcfe-7c8edfbbe3bc.png)
![image](https://user-images.githubusercontent.com/31339007/173497876-ffde8331-cc33-4cc9-8dec-50fc2ea5300e.png)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment] 2022-06-20 09:51
I cannot reproduce it. From the screenshots it looks like you're missing some information from the report, for example it looks like you have selected curved view and it also looks like you have opened another window maybe?

Please try to be very specific (even picky :)) when describing the steps because it's very important for us in order to try to reproduce and fix the issue. Thanks for reporting!

**Comment by azumukupoe** [comment] 2022-06-20 12:07
I've found a temporary workaround
Turns out it was caused by fullscreen not scaling to resized window automatically
The video gets scaled correctly when I change window resize while in fullscreen

**Comment by azumukupoe** [comment] 2022-06-24 11:59
this is how it happens for me
https://user-images.githubusercontent.com/31339007/175529701-3dc1a822-2b74-44fb-b9fc-109392e420ac.mp4

**Comment by svillar** [comment] 2022-06-27 12:22
Do you have any extension installed? It might be the case that it interferes with the content somehow

**Comment by azumukupoe** [comment] 2022-06-27 13:10
> Do you have any extension installed? It might be the case that it interferes with the content somehow

disabling them didn't change the behavior

> Also have you changed display density and or DPI?

![image](https://user-images.githubusercontent.com/31339007/175949388-36f5fb74-7bbd-4868-b185-5db87dfbea5b.png)

**Comment by svillar** [comment] 2022-07-05 10:44
So after a lot of testing we're unable to reproduce this. I believe it was fixed at some point in main.

We're releasing 1.0 soon so I encourage you to retest with the new version.

**Comment by svillar** [comment] 2022-07-25 07:41
> > So after a lot of testing we're unable to reproduce this. I believe it was fixed at some point in main.
> > We're releasing 1.0 soon so I encourage you to retest with the new version.
> 
> the issue persists in the new version

OK then there must be some difference in the configuration you're using. Perhaps you have enabled some experimental feature?

**Comment by svillar** [comment] 2022-10-11 15:38
The reporter hasn't provided more info in months. Closing this now. Please do reopen if you still experience the issue.

**Closed by svillar** 2022-10-11 15:38 UTC
Labels: bug, question, priority-low
