### ISSUE TITLE
Three JS XR flickering edges in Pico 4

### ISSUE THREAD

**Issue by user080975** [Igalia/wolvic#559] opened 2023-03-16 13:09 UTC
Hi,

When viewing a Three JS XR scene in Wolvic browser in Pico 4, the edges start flickering and appear jagged during head movements, even with anti-aliasing turned on. This issue doesn't happen in Oculus Quest. 

Examples can be found here:

https://my.matterport.com/show/?m=PikRwx96eQW&brand=0&help=0&dh=0&gt=0&hr=0&f=0&vr=0&play=1&tourcta=0&log=0&wh=0&hl=0&qs=1&mls=2&pin=0&portal=0&fp=0

https://threejs.org/examples/?q=xr#webxr_vr_panorama_depth

Is there a way to mitigate this issue? 

Thank You!

**Comment by svillar** [comment] 2023-03-17 12:18
I can't honestly reproduce what you describe neither in matterport nor in the threejs example.

Which version are you using in both devices?

Could you get some screenshot demonstrating the problem?

Thanks

**Comment by user080975** [comment] 2023-03-17 16:27
Were you able to try this specifically on a Pico 3 or Pico 4 VR headset? I'm using the latest OS version on the Pico as well as the latest Wolvic browser version. 

Whenever I try to do a screen recording, the result appears as a 2D recording and isn't very visible. However the issue does occur when in immersive 3D mode.

**Comment by svillar** [comment] 2023-03-17 16:34
> Were you able to try this specifically on a Pico 3 or Pico 4 VR headset? I'm using the latest OS version on the Pico as well as the latest Wolvic browser version.
> 
> Whenever I try to do a screen recording, the result appears as a 2D recording and isn't very visible. However the issue does occur when in immersive 3D mode.

Pico 4 controllers have a button to take screenshots, maybe that can make it? Or is it only visible in motion?

**Comment by user080975** [comment] 2023-03-18 20:45
Okay I was able to make a screen recording showing the flicking edge issue. If you download the zip folder here and open the recording, zoom in a bit and look at the areas in the screenshots marked in red. You will see that the edges start flickering when moving, even slightly:

https://we.tl/t-oNOeo51l91

To test this, you need to first open the Matterport link and then click anywhere to transition and then the issue will start.

**Comment by user080975** [comment] 2023-03-19 22:39
It almost seems like enabling 2X or 4X MSAA has no effect in the Pico 4. I tried both settings and still getting jagged edges on movement.

**Comment by svillar** [comment] 2023-03-20 09:22
The fact that you only see that on those windows makes me think it's basically a [moire effect](https://en.wikipedia.org/wiki/Moiré_pattern). Note that no other edges show that behaviour. Don't you see the same in Pico browser for example?

**Comment by user080975** [comment] 2023-03-20 10:01
Can you please zoom into the video recordings I just made and look at the areas marked in red? The jagged edges appear all over, not only in windows. 

https://we.tl/t-WIkEBMl6CQ

Can you please also try entering VR mode with this link in a Pico 4 and move around a bit?
https://my.matterport.com/show/?m=pymrVMyjeQz&aa=1

You can then see that the jagged edges occur in many mesh edges. 

This same link when visited via the Oculus Quest browser has barely any jagged edges.

**Comment by svillar** [comment] 2023-03-21 10:31
> Can you please zoom into the video recordings I just made and look at the areas marked in red? The jagged edges appear all over, not only in windows.
> 
> https://we.tl/t-WIkEBMl6CQ
> 
> Can you please also try entering VR mode with this link in a Pico 4 and move around a bit? https://my.matterport.com/show/?m=pymrVMyjeQz&aa=1
> 
> You can then see that the jagged edges occur in many mesh edges.
> 
> This same link when visited via the Oculus Quest browser has barely any jagged edges.

Now I see what you mean. So there are indeed aliasing issues, but I have doubts about whether that it has anything to do with Pico. There are no differences among platforms on that regards. I suspect that the page is serving us higher res images for the Quest because it's their supported device. Note that in the case of Pico they are also showing a pair of generic controllers, so I guess for non Meta devices they basically just play safe and send lower res images.

**Comment by user080975** [comment] 2023-03-21 19:18
Can you please try this Three JS example in the Pico 4? You'll notice that the edges of meshes really flicker a lot all over the place. In this case there's no image sampling occurring:

https://threejs.org/examples/?q=xr#webxr_vr_rollercoaster

**Comment by svillar** [comment] 2023-03-21 21:38
> Can you please try this Three JS example in the Pico 4? You'll notice that the edges of meshes really flicker a lot all over the place. In this case there's no image sampling occurring:
> 
> https://threejs.org/examples/?q=xr#webxr_vr_rollercoaster

Yes I had. Aliasing looks indeed a bit worst than in Meta but at the very same level than the Pico browser. I don't see any difference with Wolvic. Have you tried that?

I haven't checked in detail (will do at some point) with the inspector, but it might be the case that the webgl canvas is created without antialiasing support.

**Comment by user080975** [comment] 2023-03-21 21:49
I also posted a ticket on the Pico developer forum a while ago and forgot about it since there was no response for a long time. Then I noticed that they replied a month ago and said they don't see any anti alias issue even though it's there...

I just replied to the ticket as well but they don't seem to active about it:
https://developer-global.pico-interactive.com/community/post/7172825319102939142

**Comment by svillar** [comment] 2023-03-21 22:32
> Yea I checked with the Pico browser and noticed similar results. I don’t understand 100% how WebGL works but it seems like Wolvic and Pico browser behave similarly when it comes to anti aliasing.
> 
> Normally on Android shouldn’t different browsers execute their own implementation of WebGL? Or is it like in iOS where all browsers are basically Safari at their core?

Yes, in this case Pico is using Chromium and Wolvic is using Gecko, two completely different codebases and both are showing the same issue, that's what makes me think that this is not an engine issue (very unlikely), but the demo designers not using antialiasing for that demo.

**Comment by user080975** [comment] 2023-03-22 00:09
What’s strange is that in Three JS after setting antialias to true, all meshes appear smooth in Quest browser, but the exact same scene in Pico browser results in jagged edges, as if antialias has no effect, even though both are based on Chromium.

Do you know why this might be case or have any recommendations? I’m really at a loss because from the front end in Pico browser and Wolvic, antialias doesn’t seem to have any effect and effect composer won’t work in WebXR.

**Comment by svillar** [comment] 2023-03-22 11:44
> What’s strange is that in Three JS after setting antialias to true, all meshes appear smooth in Quest browser, but the exact same scene in Pico browser results in jagged edges, as if antialias has no effect, even though both are based on Chromium.
> 
> Do you know why this might be case or have any recommendations? I’m really at a loss because from the front end in Pico browser and Wolvic, antialias doesn’t seem to have any effect and effect composer won’t work in WebXR.

All I can think of is that there are two ways to create a WebXR compatible WebGL canvas. In the [specs](https://immersive-web.github.io/webxr/#contextcompatibility) you could see how one could use the `xrCompatible` attribute or call `makeXRCompatible` (recommented). They're indeed both Chromium based, but using different versions and maybe with different downstream patches applied, really don't know as I don't have access to them.

**Closed** 2023-03-26 07:05 UTC
